namespace SqlServerSimulator.Parser;

enum AtAtKeyword
{
    _ = 0, // "Default" value for the enum, indicating not a keyword.
    Connections,
    CpuBusy,
    CursorRows,
    DateFirst,
    Dbts,
    Error,
    FetchStatus,
    Identity,
    Idle,
    IoBusy,
    LangId,
    Language,
    LockTimeout,
    MaxConnections,
    MaxPrecision,
    MicrosoftVersion,
    NestLevel,
    Options,
    PackReceived,
    PacketErrors,
    PackSent,
    ProcId,
    RemServer,
    RowCount,
    ServerName,
    ServiceName,
    SpId,
    TextSize,
    TimeTicks,
    TotalErrors,
    TotalRead,
    TotalWrite,
    TranCount,
    Version
}
