using SqlServerSimulator.Parser.Tokens;
using SqlServerSimulator.Storage;

namespace SqlServerSimulator.Parser.Expressions;

/// <summary>
/// Discriminator for the window functions the simulator models.
/// EF Core 10 emits <c>ROW_NUMBER</c> for top-N / Skip+Take and aggregate
/// windows (<c>SUM/AVG/COUNT/MIN/MAX/STDEV/...</c> with <c>OVER</c>) for
/// grouped totals broadcast across detail rows. <c>RANK</c> /
/// <c>DENSE_RANK</c> and the analytic family aren't generated by idiomatic
/// LINQ, so adding them is left to a follow-up bundle.
/// </summary>
internal enum WindowKind
{
    RowNumber,
    Aggregate,
}

/// <summary>
/// SQL window function call (<c>ROW_NUMBER() OVER(...)</c> or
/// <c>SUM/AVG/COUNT/MIN/MAX/STDEV/STDEVP/VAR/VARP/COUNT_BIG/CHECKSUM_AGG/APPROX_COUNT_DISTINCT
/// (...) OVER (PARTITION BY ...)</c>). Like <see cref="AggregateExpression"/>,
/// the value can't be computed row-by-row in isolation — the executor
/// buffers the post-WHERE tuple stream, partitions rows by
/// <see cref="PartitionBy"/>, and either sorts each partition by
/// <see cref="OrderBy"/> + assigns ROW_NUMBER ranks, or runs an
/// <see cref="Aggregator"/> through the partition + broadcasts the
/// per-partition result, before binding the per-tuple result via
/// <see cref="BindResult"/>.
/// </summary>
/// <remarks>
/// EF Core 10's emission shape: ROW_NUMBER lives inside an inner SELECT
/// that's wrapped as a derived table; the outer query filters via
/// <c>WHERE row &lt;= N</c> (Take) or <c>WHERE 1 &lt; row AND row &lt;= K</c>
/// (Skip+Take). Aggregate windows broadcast a per-group total to the detail
/// rows. Frame specifications (<c>ROWS BETWEEN</c> / <c>RANGE BETWEEN</c>)
/// aren't modeled — they don't apply to ROW_NUMBER and the simulator
/// accepts only the implicit-frame default for aggregates (whole partition
/// when no ORDER BY is present in OVER). ORDER BY inside OVER for
/// aggregates raises <see cref="NotSupportedException"/> rather than
/// silently picking the wrong frame semantics; the cumulative-running-total
/// shape that requires it is rare in EF-emitted SQL and can be revisited
/// when one shows up.
/// </remarks>
internal sealed class WindowExpression : Expression
{
    public readonly WindowKind Kind;

    public readonly Expression[] PartitionBy;

    public readonly OrderBySpec[] OrderBy;

    /// <summary>
    /// For <see cref="WindowKind.Aggregate"/>, the wrapped aggregate
    /// expression (kind, operand, etc.). Null for <see cref="WindowKind.RowNumber"/>.
    /// The aggregate's own <see cref="AggregateExpression.BindResult"/> is
    /// never called when wrapped — only the surrounding window's
    /// <see cref="BindResult"/> is, since the aggregate's runtime path goes
    /// through the window's bound value.
    /// </summary>
    public readonly AggregateExpression? AggregateInfo;

    private SqlValue cachedResult;

    private bool resultBound;

    private WindowExpression(WindowKind kind, Expression[] partitionBy, OrderBySpec[] orderBy, AggregateExpression? aggregateInfo)
    {
        this.Kind = kind;
        this.PartitionBy = partitionBy;
        this.OrderBy = orderBy;
        this.AggregateInfo = aggregateInfo;
    }

    private static WindowExpression Register(ParserContext context, WindowExpression expression)
    {
        if (!context.AllowsWindowExpressions)
            throw SimulatedSqlException.WindowedFunctionInWrongClause();
        context.WindowCollector?.Add(expression);
        return expression;
    }

    /// <summary>
    /// Sets this instance's value for the row currently being projected.
    /// The Selection executor calls this once per buffered tuple, just
    /// before running the projection expressions, with either the
    /// precomputed row number (ROW_NUMBER) or the per-partition aggregate
    /// result (aggregate windows).
    /// </summary>
    internal void BindResult(SqlValue value)
    {
        this.cachedResult = value;
        this.resultBound = true;
    }

    public override SqlValue Run(RuntimeContext runtime) =>
        this.resultBound
            ? this.cachedResult
            : throw new InvalidOperationException("WindowExpression.Run was called before its result was bound; this indicates the Selection executor didn't recognize it as a window function.");

    public override SqlType GetSqlType(Func<MultiPartName, SqlType> resolveColumnType) => this.Kind switch
    {
        WindowKind.RowNumber => SqlType.BigInt,
        WindowKind.Aggregate => this.AggregateInfo!.GetSqlType(resolveColumnType),
        _ => throw new InvalidOperationException($"Unknown window kind {this.Kind}."),
    };

    /// <summary>
    /// Parses <c>ROW_NUMBER() OVER(... )</c> — entered with the cursor on
    /// the <c>)</c> closing the empty argument list. Consumes the
    /// <c>OVER ( [PARTITION BY ...] ORDER BY ... )</c> clause and leaves
    /// the cursor on the OVER's closing <c>)</c>, matching the
    /// <see cref="Expression.Parse"/> dispatch's lookahead contract.
    /// </summary>
    public static WindowExpression ParseRowNumber(ParserContext context)
    {
        if (context.Token is not Operator { Character: ')' })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        if (context.GetNextRequired() is not ReservedKeyword { Keyword: Keyword.Over })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        if (context.GetNextRequired() is not Operator { Character: '(' })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        context.MoveNextRequired();

        var partitionBy = ParseOptionalPartitionBy(context);

        // ROW_NUMBER requires ORDER BY inside the OVER clause; SQL Server
        // raises Msg 4112 otherwise. The simulator surfaces a generic
        // syntax error to keep the error-factory surface lean — EF
        // Core never emits ROW_NUMBER without ORDER BY.
        if (context.Token is not ReservedKeyword { Keyword: Keyword.Order })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        if (context.GetNextRequired() is not ReservedKeyword { Keyword: Keyword.By })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        var orderBy = ParseOrderByList(context);

        RejectFrameSpec(context);

        return context.Token is not Operator { Character: ')' }
            ? throw SimulatedSqlException.SyntaxErrorNear(context)
            : Register(context, new WindowExpression(WindowKind.RowNumber, partitionBy, orderBy, aggregateInfo: null));
    }

    /// <summary>
    /// Wraps an aggregate function that's followed by <c>OVER (...)</c>.
    /// Entered with cursor on the <c>OVER</c> keyword. Pops the just-parsed
    /// aggregate from the surrounding <see cref="ParserContext.AggregateCollector"/>
    /// (since it's evaluated through the window infrastructure rather than
    /// the GROUP BY pass), parses the OVER clause, and registers the
    /// resulting <see cref="WindowExpression"/> with
    /// <see cref="ParserContext.WindowCollector"/>. Leaves the cursor on
    /// the OVER's closing <c>)</c>.
    /// </summary>
    public static WindowExpression WrapAggregate(AggregateExpression aggregate, ParserContext context)
    {
        if (aggregate.Distinct)
            throw SimulatedSqlException.DistinctNotAllowedInOver();
        if (aggregate.Kind == AggregateKind.StringAgg)
            throw SimulatedSqlException.FunctionNotValidForOver("string_agg");

        // The aggregate auto-registered with AggregateCollector during its
        // own Parse; remove it now that the window wrapper takes over the
        // evaluation. Aggregates inside windows must NOT also count in the
        // outer aggregate set, otherwise the executor's window+aggregate
        // mutual-exclusion check would fire on every aggregate window.
        var aggCollector = context.AggregateCollector;
        if (aggCollector is not null && aggCollector.Count > 0 && ReferenceEquals(aggCollector[^1], aggregate))
            aggCollector.RemoveAt(aggCollector.Count - 1);

        if (context.GetNextRequired() is not Operator { Character: '(' })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        context.MoveNextRequired();

        var partitionBy = ParseOptionalPartitionBy(context);

        if (context.Token is ReservedKeyword { Keyword: Keyword.Order })
            throw new NotSupportedException("ORDER BY inside the OVER clause for an aggregate window function isn't modeled (only the implicit-frame whole-partition default is supported); rewrite without ORDER BY in OVER.");

        RejectFrameSpec(context);

        return context.Token is not Operator { Character: ')' }
            ? throw SimulatedSqlException.SyntaxErrorNear(context)
            : Register(context, new WindowExpression(WindowKind.Aggregate, partitionBy, [], aggregate));
    }

    /// <summary>
    /// Parses an optional <c>PARTITION BY expr [, expr]*</c> clause inside
    /// an OVER. Entered with cursor on the first token of the OVER body; on
    /// return, cursor is on the next OVER-body lookahead token (typically
    /// <c>ORDER</c>, <c>ROWS</c>, <c>RANGE</c>, or the closing <c>)</c>).
    /// </summary>
    private static Expression[] ParseOptionalPartitionBy(ParserContext context) =>
        context.Token is not UnquotedString { ContextualKeyword: ContextualKeyword.Partition }
            ? []
            : context.GetNextRequired() is not ReservedKeyword { Keyword: Keyword.By }
                ? throw SimulatedSqlException.SyntaxErrorNear(context)
                : ParseExpressionList(context);

    /// <summary>
    /// Rejects an explicit frame specification (<c>ROWS BETWEEN</c> /
    /// <c>RANGE BETWEEN</c>) at the lookahead-after-ORDER-BY position. Frame
    /// specs aren't modeled by the simulator; EF Core 10 doesn't emit them
    /// from idiomatic LINQ. Distinct from the implicit defaults that ROW_NUMBER
    /// (no frame applies) and aggregate windows (whole partition when no
    /// ORDER BY) use natively.
    /// </summary>
    private static void RejectFrameSpec(ParserContext context)
    {
        switch (context.Token)
        {
            case UnquotedString { ContextualKeyword: ContextualKeyword.Rows }:
                throw new NotSupportedException("Explicit window frame ROWS BETWEEN inside OVER isn't modeled; only the implicit default frame is supported.");
            case UnquotedString { ContextualKeyword: ContextualKeyword.Range }:
                throw new NotSupportedException("Explicit window frame RANGE BETWEEN inside OVER isn't modeled; only the implicit default frame is supported.");
        }
    }

    /// <summary>
    /// Parses a comma-separated list of expressions, used by PARTITION BY.
    /// Cursor is on the first token of the first expression on entry; on
    /// return the cursor is at the lookahead-after-list token (typically
    /// <c>ORDER</c> for the OVER's second clause).
    /// </summary>
    private static Expression[] ParseExpressionList(ParserContext context)
    {
        var items = new List<Expression>();
        while (true)
        {
            context.MoveNextRequired();
            items.Add(Expression.Parse(context));
            if (context.Token is not Operator { Character: ',' })
                break;
        }
        return [.. items];
    }

    /// <summary>
    /// Parses a comma-separated list of <c>expr [ASC|DESC]</c> for the
    /// OVER's ORDER BY. Cursor is on the first token of the first
    /// expression on entry; on return the cursor is at the lookahead-
    /// after-list token (typically the OVER's closing <c>)</c>).
    /// </summary>
    private static OrderBySpec[] ParseOrderByList(ParserContext context)
    {
        var items = new List<OrderBySpec>();
        while (true)
        {
            context.MoveNextRequired();
            var expr = Expression.Parse(context);
            var descending = false;
            switch (context.Token)
            {
                case ReservedKeyword { Keyword: Keyword.Asc }:
                    context.MoveNextOptional();
                    break;
                case ReservedKeyword { Keyword: Keyword.Desc }:
                    descending = true;
                    context.MoveNextOptional();
                    break;
            }
            items.Add(OrderBySpec.FromExpression(expr, descending));
            if (context.Token is not Operator { Character: ',' })
                break;
        }
        return [.. items];
    }

    internal override string DebugDisplay()
    {
        var name = this.Kind switch
        {
            WindowKind.RowNumber => "ROW_NUMBER()",
            WindowKind.Aggregate => this.AggregateInfo!.DebugDisplay(),
            _ => this.Kind.ToString(),
        };
        var partitionPart = this.PartitionBy.Length == 0
            ? ""
            : "PARTITION BY " + string.Join(", ", this.PartitionBy.Select(p => p.DebugDisplay()));
        // OVER's ORDER BY is always expression-based — ordinals only apply
        // to a SELECT projection's ORDER BY, which is parsed elsewhere.
        var orderPart = this.OrderBy.Length == 0
            ? ""
            : "ORDER BY " + string.Join(", ", this.OrderBy.Select(o => o.Expr!.DebugDisplay() + (o.Descending ? " DESC" : "")));
        var separator = partitionPart.Length > 0 && orderPart.Length > 0 ? " " : "";
        return $"{name} OVER({partitionPart}{separator}{orderPart})";
    }
}
