using SqlServerSimulator.Parser.Tokens;
using SqlServerSimulator.Storage;

namespace SqlServerSimulator.Parser.Expressions;

/// <summary>
/// Discriminator for the window functions the simulator models.
/// EF Core 10 only emits <c>ROW_NUMBER</c>; <c>RANK</c> / <c>DENSE_RANK</c>
/// and the analytic family aren't generated by idiomatic LINQ, so adding
/// them is left to a follow-up bundle.
/// </summary>
internal enum WindowKind
{
    RowNumber,
}

/// <summary>
/// SQL window function call (currently <c>ROW_NUMBER() OVER(...)</c>).
/// Like <see cref="AggregateExpression"/>, the value can't be computed
/// row-by-row in isolation — the executor buffers the post-WHERE tuple
/// stream, partitions rows by <see cref="PartitionBy"/>, sorts each
/// partition by <see cref="OrderBy"/>, and assigns sequence numbers
/// before binding the per-tuple result via <see cref="BindResult"/>.
/// </summary>
/// <remarks>
/// EF Core 10's emission shape: the entire window function lives inside
/// an inner SELECT that's wrapped as a derived table; the outer query
/// filters via <c>WHERE row &lt;= N</c> (Take) or
/// <c>WHERE 1 &lt; row AND row &lt;= K</c> (Skip+Take). Frame
/// specifications (<c>ROWS BETWEEN</c> / <c>RANGE BETWEEN</c>) aren't
/// modeled — they don't apply to <c>ROW_NUMBER</c> anyway.
/// </remarks>
internal sealed class WindowExpression : Expression
{
    public readonly WindowKind Kind;

    public readonly Expression[] PartitionBy;

    public readonly OrderBySpec[] OrderBy;

    private SqlValue cachedResult;

    private bool resultBound;

    private WindowExpression(WindowKind kind, Expression[] partitionBy, OrderBySpec[] orderBy)
    {
        this.Kind = kind;
        this.PartitionBy = partitionBy;
        this.OrderBy = orderBy;
    }

    private static WindowExpression Register(ParserContext context, WindowExpression expression)
    {
        context.WindowCollector?.Add(expression);
        return expression;
    }

    /// <summary>
    /// Sets this instance's value for the row currently being projected.
    /// The Selection executor calls this once per buffered tuple, just
    /// before running the projection expressions, with the precomputed
    /// row number for that tuple.
    /// </summary>
    internal void BindResult(SqlValue value)
    {
        this.cachedResult = value;
        this.resultBound = true;
    }

    public override SqlValue Run(Func<MultiPartName, SqlValue> getColumnValue) =>
        this.resultBound
            ? this.cachedResult
            : throw new InvalidOperationException("WindowExpression.Run was called before its result was bound; this indicates the Selection executor didn't recognize it as a window function.");

    public override SqlType GetSqlType(Func<MultiPartName, SqlType> resolveColumnType) => this.Kind switch
    {
        WindowKind.RowNumber => SqlType.BigInt,
        _ => throw new InvalidOperationException($"Unknown window kind {this.Kind}."),
    };

    /// <summary>
    /// Parses <c>ROW_NUMBER() OVER(... )</c> — entered with the cursor on
    /// the <c>)</c> closing the empty argument list. Consumes the
    /// <c>OVER ( [PARTITION BY ...] ORDER BY ... )</c> clause and leaves
    /// the cursor on the OVER's closing <c>)</c>, matching the
    /// <see cref="Expression.Parse"/> dispatch's lookahead contract.
    /// </summary>
    public static WindowExpression ParseRowNumber(ParserContext context)
    {
        if (context.Token is not Operator { Character: ')' })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        if (context.GetNextRequired() is not ReservedKeyword { Keyword: Keyword.Over })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        if (context.GetNextRequired() is not Operator { Character: '(' })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        context.MoveNextRequired();

        var partitionBy = Array.Empty<Expression>();
        if (context.MatchContextual(ContextualKeyword.Partition))
        {
            if (context.GetNextRequired() is not ReservedKeyword { Keyword: Keyword.By })
                throw SimulatedSqlException.SyntaxErrorNear(context);
            partitionBy = ParseExpressionList(context);
        }

        // ROW_NUMBER requires ORDER BY inside the OVER clause; SQL Server
        // raises Msg 4112 otherwise. The simulator surfaces a generic
        // syntax error to keep the error-factory surface lean — EF
        // Core never emits ROW_NUMBER without ORDER BY.
        if (context.Token is not ReservedKeyword { Keyword: Keyword.Order })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        if (context.GetNextRequired() is not ReservedKeyword { Keyword: Keyword.By })
            throw SimulatedSqlException.SyntaxErrorNear(context);
        var orderBy = ParseOrderByList(context);

        return context.Token is not Operator { Character: ')' }
            ? throw SimulatedSqlException.SyntaxErrorNear(context)
            : Register(context, new WindowExpression(WindowKind.RowNumber, partitionBy, orderBy));
    }

    /// <summary>
    /// Parses a comma-separated list of expressions, used by PARTITION BY.
    /// Cursor is on the first token of the first expression on entry; on
    /// return the cursor is at the lookahead-after-list token (typically
    /// <c>ORDER</c> for the OVER's second clause).
    /// </summary>
    private static Expression[] ParseExpressionList(ParserContext context)
    {
        var items = new List<Expression>();
        while (true)
        {
            context.MoveNextRequired();
            items.Add(Expression.Parse(context));
            if (context.Token is not Operator { Character: ',' })
                break;
        }
        return [.. items];
    }

    /// <summary>
    /// Parses a comma-separated list of <c>expr [ASC|DESC]</c> for the
    /// OVER's ORDER BY. Cursor is on the first token of the first
    /// expression on entry; on return the cursor is at the lookahead-
    /// after-list token (typically the OVER's closing <c>)</c>).
    /// </summary>
    private static OrderBySpec[] ParseOrderByList(ParserContext context)
    {
        var items = new List<OrderBySpec>();
        while (true)
        {
            context.MoveNextRequired();
            var expr = Expression.Parse(context);
            var descending = false;
            if (context.Token is ReservedKeyword { Keyword: Keyword.Asc })
            {
                context.MoveNextOptional();
            }
            else if (context.Token is ReservedKeyword { Keyword: Keyword.Desc })
            {
                descending = true;
                context.MoveNextOptional();
            }
            items.Add(OrderBySpec.FromExpression(expr, descending));
            if (context.Token is not Operator { Character: ',' })
                break;
        }
        return [.. items];
    }

    internal override string DebugDisplay()
    {
        var name = this.Kind switch
        {
            WindowKind.RowNumber => "ROW_NUMBER",
            _ => this.Kind.ToString(),
        };
        var partitionPart = this.PartitionBy.Length == 0
            ? ""
            : "PARTITION BY " + string.Join(", ", this.PartitionBy.Select(p => p.DebugDisplay())) + " ";
        // OVER's ORDER BY is always expression-based — ordinals only apply
        // to a SELECT projection's ORDER BY, which is parsed elsewhere.
        var orderParts = this.OrderBy.Select(o => o.Expr!.DebugDisplay() + (o.Descending ? " DESC" : ""));
        return $"{name}() OVER({partitionPart}ORDER BY {string.Join(", ", orderParts)})";
    }
}
