using Microsoft.EntityFrameworkCore;

namespace SqlServerSimulator;

/// <summary>
/// Exercises the simulator's <c>IDENTITY</c> column support through EF Core.
/// SaveChanges on an EF-managed identity entity emits
/// <c>INSERT ... OUTPUT INSERTED.Id</c> (single row) or <c>MERGE INTO ... OUTPUT</c>
/// (multi-row) — neither is parsed yet, so that path is pinned as a gap by
/// <see cref="Insert_IdentityKey_AwaitsOutputClauseSupport"/>. The other
/// tests exercise three EF Core paths that <i>don't</i> require
/// <c>OUTPUT</c>: read-only LINQ, <c>SqlQueryRaw</c> against the identity
/// scalars, and <c>SaveChanges</c> with <c>DatabaseGenerated.None</c> + <c>SET IDENTITY_INSERT ON</c>.
/// </summary>
[TestClass]
public class EFCoreIdentity
{
    public TestContext TestContext { get; set; } = null!;

    [TestMethod]
    public void Insert_IdentityKey_AwaitsOutputClauseSupport()
    {
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());

        var widget = new Widget { Name = "First" };
        _ = context.Widgets.Add(widget);

        var ex = Assert.Throws<DbUpdateException>(() => context.SaveChanges());
        StringAssert.Contains(ex.InnerException?.Message ?? "", "OUTPUT");
    }

    [TestMethod]
    public void Query_IdentityRows_ReturnsAutoGeneratedIds()
    {
        var simulation = TestDbContext.CreateWidgetsSimulation();
        _ = simulation
            .CreateOpenConnection()
            .CreateCommand("insert into Widgets (Name) values ('A'),('B'),('C')")
            .ExecuteNonQuery();

        using var context = new TestDbContext(simulation);
        var rows = context.Widgets.OrderBy(w => w.Id).ToArray();

        CollectionAssert.AreEqual(new[] { 1, 2, 3 }, rows.Select(w => w.Id).ToArray());
        CollectionAssert.AreEqual(new[] { "A", "B", "C" }, rows.Select(w => w.Name).ToArray());
    }

    [TestMethod]
    public void Where_FiltersByAutoGeneratedId()
    {
        var simulation = TestDbContext.CreateWidgetsSimulation();
        _ = simulation
            .CreateOpenConnection()
            .CreateCommand("insert into Widgets (Name) values ('A'),('B'),('C')")
            .ExecuteNonQuery();

        using var context = new TestDbContext(simulation);
        var name = context.Widgets.Where(w => w.Id == 2).Select(w => w.Name).Single();

        Assert.AreEqual("B", name);
    }

    [TestMethod]
    public void SqlQueryRaw_ScopeIdentity_ReturnsLastInsertedValue()
    {
        // SCOPE_IDENTITY/@@IDENTITY are simulation-wide here (not per-session) —
        // see CLAUDE.md's "session-scoped state" gap. That collapse means the
        // raw INSERT on a separate connection still updates the value EF reads.
        var simulation = TestDbContext.CreateWidgetsSimulation();
        _ = simulation
            .CreateOpenConnection()
            .CreateCommand("insert into Widgets (Name) values ('First'),('Second')")
            .ExecuteNonQuery();

        using var context = new TestDbContext(simulation);
        var sid = context.Database.SqlQueryRaw<decimal>("select SCOPE_IDENTITY() as Value").AsEnumerable().Single();
        var atid = context.Database.SqlQueryRaw<decimal>("select @@IDENTITY as Value").AsEnumerable().Single();

        Assert.AreEqual(2m, sid);
        Assert.AreEqual(2m, atid);
    }

    [TestMethod]
    public void SqlQueryRaw_IdentCurrent_ReturnsHighWaterMark()
    {
        var simulation = TestDbContext.CreateWidgetsSimulation();
        _ = simulation
            .CreateOpenConnection()
            .CreateCommand("insert into Widgets (Name) values ('A'),('B'),('C')")
            .ExecuteNonQuery();

        using var context = new TestDbContext(simulation);
        var ic = context.Database.SqlQueryRaw<decimal>("select IDENT_CURRENT('Widgets') as Value").AsEnumerable().Single();

        Assert.AreEqual(3m, ic);
    }

    [TestMethod]
    public void SqlQueryRaw_ScopeIdentity_BeforeAnyInsertIsNull()
    {
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());
        var sid = context.Database.SqlQueryRaw<decimal?>("select SCOPE_IDENTITY() as Value").AsEnumerable().Single();

        Assert.IsNull(sid);
    }

    [TestMethod]
    public void SaveChanges_WithIdentityInsertOn_PersistsExplicitId()
    {
        var simulation = TestDbContext.CreateStickersSimulation();
        _ = simulation
            .CreateOpenConnection()
            .CreateCommand("set identity_insert Stickers on")
            .ExecuteNonQuery();

        using var context = new TestDbContext(simulation);
        _ = context.Stickers.Add(new Sticker { Id = 100, Tag = "explicit" });
        _ = context.SaveChanges();

        Assert.AreEqual("explicit", context.Stickers.Where(s => s.Id == 100).Select(s => s.Tag).Single());
    }

    [TestMethod]
    public void SaveChanges_WithIdentityInsertOn_AdvancesSeed()
    {
        // Inserting an explicit Id past the high-water mark via EF should
        // reseed the same way raw SQL does.
        var simulation = TestDbContext.CreateStickersSimulation();
        _ = simulation
            .CreateOpenConnection()
            .CreateCommand("set identity_insert Stickers on")
            .ExecuteNonQuery();

        using (var context = new TestDbContext(simulation))
        {
            _ = context.Stickers.Add(new Sticker { Id = 50, Tag = "jump" });
            _ = context.SaveChanges();
        }

        var ic = simulation
            .CreateOpenConnection()
            .CreateCommand("select IDENT_CURRENT('Stickers')")
            .ExecuteScalar();
        Assert.AreEqual(50m, ic);
    }
}
