using Microsoft.EntityFrameworkCore;

namespace SqlServerSimulator;

/// <summary>
/// Exercises the simulator's <c>IDENTITY</c> column support through EF Core's
/// SaveChanges path. EF emits <c>INSERT ... OUTPUT INSERTED.Id</c> for a
/// single new entity and <c>MERGE INTO ... USING (VALUES ...) ... OUTPUT</c>
/// for a multi-entity batch; both forms now round-trip end-to-end. Coverage
/// also includes raw <c>SqlQueryRaw</c> against the identity scalars and the
/// <c>DatabaseGenerated.None</c> + <c>SET IDENTITY_INSERT</c> escape hatch.
/// </summary>
[TestClass]
public class EFCoreIdentity
{
    public TestContext TestContext { get; set; } = null!;

    [TestMethod]
    public void SaveChanges_SingleEntity_AssignsGeneratedIdentity()
    {
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());

        var widget = new Widget { Name = "First" };
        _ = context.Widgets.Add(widget);
        _ = context.SaveChanges();

        Assert.AreEqual(1, widget.Id);
        Assert.AreEqual("First", context.Widgets.Where(w => w.Id == 1).Select(w => w.Name).Single());
    }

    [TestMethod]
    public void SaveChanges_MultipleEntities_AssignsContiguousIdentities()
    {
        // EF emits MERGE for >1 row inserts; the OUTPUT clause carries the
        // generated Ids back through a positional source column so EF can
        // rehydrate the in-memory entities.
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());

        var a = new Widget { Name = "A" };
        var b = new Widget { Name = "B" };
        var c = new Widget { Name = "C" };
        context.Widgets.AddRange(a, b, c);
        _ = context.SaveChanges();

        Assert.AreEqual(1, a.Id);
        Assert.AreEqual(2, b.Id);
        Assert.AreEqual(3, c.Id);
    }

    [TestMethod]
    public void SaveChanges_AcrossBatches_ReseedsThroughHighWaterMark()
    {
        // Each SaveChanges produces a fresh INSERT/MERGE. Identity continues
        // counting from the table's high-water mark across calls.
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation()).WithSaved(new Widget { Name = "first" });

        var pair = new[] { new Widget { Name = "second" }, new Widget { Name = "third" } };
        context.Widgets.AddRange(pair);
        _ = context.SaveChanges();

        Assert.AreEqual(2, pair[0].Id);
        Assert.AreEqual(3, pair[1].Id);
    }

    [TestMethod]
    public void Query_IdentityRows_ReturnsAutoGeneratedIds()
    {
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());
        context.Widgets.AddRange(new Widget { Name = "A" }, new Widget { Name = "B" }, new Widget { Name = "C" });
        _ = context.SaveChanges();

        var rows = context.Widgets.OrderBy(w => w.Id).ToArray();
        CollectionAssert.AreEqual(new[] { 1, 2, 3 }, rows.Select(w => w.Id).ToArray());
        CollectionAssert.AreEqual(new[] { "A", "B", "C" }, rows.Select(w => w.Name).ToArray());
    }

    [TestMethod]
    public void Where_FiltersByAutoGeneratedId()
    {
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());
        context.Widgets.AddRange(new Widget { Name = "A" }, new Widget { Name = "B" }, new Widget { Name = "C" });
        _ = context.SaveChanges();

        var name = context.Widgets.Where(w => w.Id == 2).Select(w => w.Name).Single();
        Assert.AreEqual("B", name);
    }

    [TestMethod]
    public void SqlQueryRaw_ScopeIdentity_ReturnsLastInsertedValue()
    {
        // SCOPE_IDENTITY/@@IDENTITY are per-session — the priming INSERT and
        // the read have to share the EF context's connection.
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());
        context.Database.OpenConnection();
        using (var cmd = context.Database.GetDbConnection().CreateCommand())
        {
            cmd.CommandText = "insert Widgets (Name) values ('First'),('Second')";
            _ = cmd.ExecuteNonQuery();
        }

        var sid = context.Database.SqlQueryRaw<decimal>("select SCOPE_IDENTITY() as Value").AsEnumerable().Single();
        var atid = context.Database.SqlQueryRaw<decimal>("select @@IDENTITY as Value").AsEnumerable().Single();

        Assert.AreEqual(2m, sid);
        Assert.AreEqual(2m, atid);
    }

    [TestMethod]
    public void SqlQueryRaw_IdentCurrent_ReturnsHighWaterMark()
    {
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());
        context.Widgets.AddRange(new Widget { Name = "A" }, new Widget { Name = "B" }, new Widget { Name = "C" });
        _ = context.SaveChanges();

        var ic = context.Database.SqlQueryRaw<decimal>("select IDENT_CURRENT('Widgets') as Value").AsEnumerable().Single();
        Assert.AreEqual(3m, ic);
    }

    [TestMethod]
    public void SqlQueryRaw_ScopeIdentity_BeforeAnyInsertIsNull()
    {
        using var context = new TestDbContext(TestDbContext.CreateWidgetsSimulation());
        var sid = context.Database.SqlQueryRaw<decimal?>("select SCOPE_IDENTITY() as Value").AsEnumerable().Single();

        Assert.IsNull(sid);
    }

    [TestMethod]
    public void SaveChanges_WithIdentityInsertOn_PersistsExplicitId()
    {
        // SET IDENTITY_INSERT scopes to the connection — issue it on the EF
        // context's connection so SaveChanges runs under the same flag.
        using var context = new TestDbContext(TestDbContext.CreateStickersSimulation());
        context.Database.OpenConnection();
        _ = context.Database.ExecuteSqlRaw("set identity_insert Stickers on");

        _ = context.Stickers.Add(new Sticker { Id = 100, Tag = "explicit" });
        _ = context.SaveChanges();

        Assert.AreEqual("explicit", context.Stickers.Where(s => s.Id == 100).Select(s => s.Tag).Single());
    }

    [TestMethod]
    public void SaveChanges_WithIdentityInsertOn_AdvancesSeed()
    {
        // Inserting an explicit Id past the high-water mark via EF should
        // reseed the same way raw SQL does. SET IDENTITY_INSERT and the
        // SaveChanges insert have to share the connection; IDENT_CURRENT
        // (database-scoped, not session-scoped) is observable from anywhere.
        var simulation = TestDbContext.CreateStickersSimulation();
        using (var context = new TestDbContext(simulation))
        {
            context.Database.OpenConnection();
            _ = context.Database.ExecuteSqlRaw("set identity_insert Stickers on");
            _ = context.Stickers.Add(new Sticker { Id = 50, Tag = "jump" });
            _ = context.SaveChanges();
        }

        var ic = simulation
            .CreateOpenConnection()
            .CreateCommand("select IDENT_CURRENT('Stickers')")
            .ExecuteScalar();
        Assert.AreEqual(50m, ic);
    }
}
