using System.Collections.Frozen;

namespace SqlServerSimulator;

/// <summary>
/// Probed-and-baked metadata for SQL Server's collation catalog. The
/// <see cref="KnownPrefixes"/> table maps each of the 124 distinct
/// <c>sys.fn_helpcollations()</c> name-prefixes to the .NET culture +
/// human-readable prefix used in the description column. The
/// <see cref="SqlServerSortOrders"/> table covers the SQL_* family —
/// each name carries a unique "SQL Server Sort Order N on Code Page M"
/// stamp in its description that isn't derivable from the name grammar.
/// </summary>
internal abstract partial class Collation
{
    /// <summary>
    /// Catalog entry for a recognized collation-name prefix. <c>CultureName</c>
    /// is the BCP-47 name passed to <see cref="System.Globalization.CultureInfo.GetCultureInfo(string)"/>;
    /// empty string = invariant culture. <c>HumanPrefix</c> is the dashed
    /// form that opens the <c>sys.fn_helpcollations()</c> description column
    /// (without the version-suffix and without trailing flags).
    /// </summary>
    internal readonly record struct PrefixInfo(string CultureName, string HumanPrefix);

    /// <summary>
    /// Catalog entry for a SQL_* family member: the Sort Order number and
    /// human prefix carried by <c>sys.fn_helpcollations()</c>'s description
    /// column. Code page is derived from the name's <c>CP*</c> token.
    /// </summary>
    internal readonly record struct SqlSortOrder(int OrderNumber, string HumanPrefix);

    /// <summary>
    /// 124 distinct prefixes from <c>sys.fn_helpcollations()</c> on
    /// SQL Server 2025. Each maps to the .NET culture whose
    /// <see cref="System.Globalization.CompareInfo"/> drives comparison +
    /// the human-readable form used in the description column. Cultures
    /// without a clean .NET equivalent map to the invariant culture
    /// (empty string) — comparison body still routes through that culture's
    /// CompareInfo, equality / case-folding remain correct, but sort-key
    /// tiebreakers may diverge (the same fidelity bar as the existing
    /// locale-comparer collations documented in <c>collations.md</c>).
    /// </summary>
    internal static readonly FrozenDictionary<string, PrefixInfo> KnownPrefixes =
        new Dictionary<string, PrefixInfo>(StringComparer.OrdinalIgnoreCase)
        {
            // Latin1_General — invariant culture, the simulator's default base
            ["Latin1_General"] = new("", "Latin1-General"),

            // Locales with clean .NET culture equivalents
            ["Albanian"] = new("sq", "Albanian"),
            ["Arabic"] = new("ar", "Arabic"),
            ["Assamese"] = new("as", "Assamese"),
            ["Azeri_Cyrillic"] = new("az-Cyrl", "Azeri-Cyrillic"),
            ["Azeri_Latin"] = new("az-Latn", "Azeri-Latin"),
            ["Bashkir"] = new("ba", "Bashkir"),
            ["Bengali"] = new("bn", "Bengali"),
            ["Bosnian_Cyrillic"] = new("bs-Cyrl", "Bosnian-Cyrillic"),
            ["Bosnian_Latin"] = new("bs-Latn", "Bosnian-Latin"),
            ["Breton"] = new("br", "Breton"),
            ["Chinese_Hong_Kong_Stroke"] = new("zh-HK", "Chinese-Hong-Kong-Stroke"),
            ["Chinese_PRC"] = new("zh-CN", "Chinese-PRC"),
            ["Chinese_PRC_Stroke"] = new("zh-CN", "Chinese-PRC-Stroke"),
            ["Chinese_Simplified_Pinyin"] = new("zh-CN", "Chinese-Simplified-Pinyin"),
            ["Chinese_Simplified_Stroke_Order"] = new("zh-CN", "Chinese-Simplified-Stroke-Order"),
            ["Chinese_Taiwan_Bopomofo"] = new("zh-TW", "Chinese-Taiwan-Bopomofo"),
            ["Chinese_Taiwan_Stroke"] = new("zh-TW", "Chinese-Taiwan-Stroke"),
            ["Chinese_Traditional_Bopomofo"] = new("zh-TW", "Chinese-Traditional-Bopomofo"),
            ["Chinese_Traditional_Pinyin"] = new("zh-TW", "Chinese-Traditional-Pinyin"),
            ["Chinese_Traditional_Stroke_Count"] = new("zh-TW", "Chinese-Traditional-Stroke-Count"),
            ["Chinese_Traditional_Stroke_Order"] = new("zh-TW", "Chinese-Traditional-Stroke-Order"),
            ["Corsican"] = new("co", "Corsican"),
            ["Croatian"] = new("hr", "Croatian"),
            ["Cyrillic_General"] = new("ru", "Cyrillic-General"),
            ["Czech"] = new("cs", "Czech"),
            ["Danish_Greenlandic"] = new("da", "Danish-Greenlandic"),
            ["Danish_Norwegian"] = new("da", "Danish-Norwegian"),
            ["Dari"] = new("prs", "Dari"),
            ["Divehi"] = new("dv", "Divehi"),
            ["Estonian"] = new("et", "Estonian"),
            ["Finnish_Swedish"] = new("fi", "Finnish-Swedish"),
            ["French"] = new("fr", "French"),
            ["Frisian"] = new("fy", "Frisian"),
            ["Georgian_Modern_Sort"] = new("ka", "Georgian-Modern-Sort"),
            ["German_PhoneBook"] = new("de", "German-PhoneBook"),
            ["Greek"] = new("el", "Greek"),
            ["Hebrew"] = new("he", "Hebrew"),
            ["Hungarian"] = new("hu", "Hungarian"),
            ["Hungarian_Technical"] = new("hu", "Hungarian-Technical"),
            ["Icelandic"] = new("is", "Icelandic"),
            ["Indic_General"] = new("", "Indic-General"),
            ["Japanese"] = new("ja", "Japanese"),
            ["Japanese_Bushu_Kakusu"] = new("ja", "Japanese-Bushu-Kakusu"),
            ["Japanese_Unicode"] = new("ja", "Japanese-Unicode"),
            ["Japanese_XJIS"] = new("ja", "Japanese-XJIS"),
            ["Kazakh"] = new("kk", "Kazakh"),
            ["Khmer"] = new("km", "Khmer"),
            ["Korean"] = new("ko", "Korean"),
            ["Korean_Wansung"] = new("ko", "Korean-Wansung"),
            ["Lao"] = new("lo", "Lao"),
            ["Latvian"] = new("lv", "Latvian"),
            ["Lithuanian"] = new("lt", "Lithuanian"),
            ["Macedonian_FYROM"] = new("mk", "Macedonian-FYROM"),
            ["Maltese"] = new("mt", "Maltese"),
            ["Maori"] = new("mi", "Maori"),
            ["Mapudungan"] = new("arn", "Mapudungan"),
            ["Modern_Spanish"] = new("es", "Modern-Spanish"),
            ["Mohawk"] = new("moh", "Mohawk"),
            ["Nepali"] = new("ne", "Nepali"),
            ["Norwegian"] = new("nb", "Norwegian"),
            ["Pashto"] = new("ps", "Pashto"),
            ["Persian"] = new("fa", "Persian"),
            ["Polish"] = new("pl", "Polish"),
            ["Romanian"] = new("ro", "Romanian"),
            ["Romansh"] = new("rm", "Romansh"),
            ["Sami_Norway"] = new("se-NO", "Sami-Norway"),
            ["Sami_Sweden_Finland"] = new("se-SE", "Sami-Sweden-Finland"),
            ["Serbian_Cyrillic"] = new("sr-Cyrl", "Serbian-Cyrillic"),
            ["Serbian_Latin"] = new("sr-Latn", "Serbian-Latin"),
            ["Slovak"] = new("sk", "Slovak"),
            ["Slovenian"] = new("sl", "Slovenian"),
            ["Syriac"] = new("syr", "Syriac"),
            ["Tamazight"] = new("", "Tamazight"),
            ["Tatar"] = new("tt", "Tatar"),
            ["Thai"] = new("th", "Thai"),
            ["Tibetan"] = new("bo", "Tibetan"),
            ["Traditional_Spanish"] = new("", "Traditional-Spanish"),
            ["Turkish"] = new("tr", "Turkish"),
            ["Turkmen"] = new("tk", "Turkmen"),
            ["Uighur"] = new("ug", "Uighur"),
            ["Ukrainian"] = new("uk", "Ukrainian"),
            ["Upper_Sorbian"] = new("hsb", "Upper-Sorbian"),
            ["Urdu"] = new("ur", "Urdu"),
            ["Uzbek_Latin"] = new("uz-Latn", "Uzbek-Latin"),
            ["Vietnamese"] = new("vi", "Vietnamese"),
            ["Welsh"] = new("cy", "Welsh"),
            ["Yakut"] = new("sah", "Yakut"),

            // SQL_* family — each maps to a real .NET culture; the HumanPrefix
            // here is the canonical locale name, NOT the description-row's
            // human prefix (which is per-name and lives in SqlServerSortOrders).
            // The per-name override is consulted first when generating the
            // description; this entry's HumanPrefix is the parser's fallback
            // for SQL_* names not in the SqlServerSortOrders table.
            ["SQL_1xCompat"] = new("", "Latin1-General"),
            ["SQL_AltDiction"] = new("", "Latin1-General"),
            ["SQL_AltDiction_Pref"] = new("", "Latin1-General"),
            ["SQL_AltDiction2"] = new("", "Latin1-General"),
            ["SQL_Croatian"] = new("hr", "Croatian"),
            ["SQL_Czech"] = new("cs", "Czech"),
            ["SQL_Danish_Pref"] = new("da", "Danish-Norwegian"),
            ["SQL_EBCDIC037"] = new("", "Latin1-General"),
            ["SQL_EBCDIC1141"] = new("de", "German-PhoneBook"),
            ["SQL_EBCDIC273"] = new("de", "German-PhoneBook"),
            ["SQL_EBCDIC277"] = new("da", "Danish-Norwegian"),
            ["SQL_EBCDIC277_2"] = new("da", "Danish-Norwegian"),
            ["SQL_EBCDIC278"] = new("fi", "Finnish-Swedish"),
            ["SQL_EBCDIC280"] = new("", "Latin1-General"),
            ["SQL_EBCDIC284"] = new("es", "Modern-Spanish"),
            ["SQL_EBCDIC285"] = new("", "Latin1-General"),
            ["SQL_EBCDIC297"] = new("fr", "French"),
            ["SQL_Estonian"] = new("et", "Estonian"),
            ["SQL_Hungarian"] = new("hu", "Hungarian"),
            ["SQL_Icelandic_Pref"] = new("is", "Icelandic"),
            ["SQL_Latin1_General"] = new("", "Latin1-General"),
            ["SQL_Latin1_General_Pref"] = new("", "Latin1-General"),
            ["SQL_Latvian"] = new("lv", "Latvian"),
            ["SQL_Lithuanian"] = new("lt", "Lithuanian"),
            ["SQL_MixDiction"] = new("", "Latin1-General"),
            ["SQL_Polish"] = new("pl", "Polish"),
            ["SQL_Romanian"] = new("ro", "Romanian"),
            ["SQL_Scandinavian"] = new("fi", "Finnish-Swedish"),
            ["SQL_Scandinavian_Pref"] = new("fi", "Finnish-Swedish"),
            ["SQL_Slovak"] = new("sk", "Slovak"),
            ["SQL_Slovenian"] = new("sl", "Slovenian"),
            ["SQL_SwedishPhone_Pref"] = new("fi", "Finnish-Swedish"),
            ["SQL_SwedishStd_Pref"] = new("fi", "Finnish-Swedish"),
            ["SQL_Ukrainian"] = new("uk", "Ukrainian"),
        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// SQL_* family per-name metadata — the Sort Order number and human
    /// prefix that <c>sys.fn_helpcollations()</c> stamps into the description
    /// column. Probed against SQL Server 2025 on 2026-05-21; values aren't
    /// derivable from the name grammar. 78 entries total.
    /// </summary>
    internal static readonly FrozenDictionary<string, SqlSortOrder> SqlServerSortOrders =
        new Dictionary<string, SqlSortOrder>(StringComparer.OrdinalIgnoreCase)
        {
            ["SQL_1xCompat_CP850_CI_AS"] = new(49, "Latin1-General"),
            ["SQL_AltDiction_CP850_CI_AI"] = new(57, "Latin1-General"),
            ["SQL_AltDiction_CP850_CI_AS"] = new(61, "Latin1-General"),
            ["SQL_AltDiction_CP850_CS_AS"] = new(55, "Latin1-General"),
            ["SQL_AltDiction_Pref_CP850_CI_AS"] = new(56, "Latin1-General"),
            ["SQL_AltDiction2_CP1253_CS_AS"] = new(122, "Latin1-General"),
            ["SQL_Croatian_CP1250_CI_AS"] = new(92, "Croatian"),
            ["SQL_Croatian_CP1250_CS_AS"] = new(91, "Croatian"),
            ["SQL_Czech_CP1250_CI_AS"] = new(84, "Czech"),
            ["SQL_Czech_CP1250_CS_AS"] = new(83, "Czech"),
            ["SQL_Danish_Pref_CP1_CI_AS"] = new(183, "Danish-Norwegian"),
            ["SQL_EBCDIC037_CP1_CS_AS"] = new(210, "Latin1-General"),
            ["SQL_EBCDIC1141_CP1_CS_AS"] = new(219, "German-PhoneBook"),
            ["SQL_EBCDIC273_CP1_CS_AS"] = new(211, "German-PhoneBook"),
            ["SQL_EBCDIC277_2_CP1_CS_AS"] = new(218, "Danish-Norwegian"),
            ["SQL_EBCDIC277_CP1_CS_AS"] = new(212, "Danish-Norwegian"),
            ["SQL_EBCDIC278_CP1_CS_AS"] = new(213, "Finnish-Swedish"),
            ["SQL_EBCDIC280_CP1_CS_AS"] = new(214, "Latin1-General"),
            ["SQL_EBCDIC284_CP1_CS_AS"] = new(215, "Modern-Spanish"),
            ["SQL_EBCDIC285_CP1_CS_AS"] = new(216, "Latin1-General"),
            ["SQL_EBCDIC297_CP1_CS_AS"] = new(217, "French"),
            ["SQL_Estonian_CP1257_CI_AS"] = new(156, "Estonian"),
            ["SQL_Estonian_CP1257_CS_AS"] = new(155, "Estonian"),
            ["SQL_Hungarian_CP1250_CI_AS"] = new(86, "Hungarian"),
            ["SQL_Hungarian_CP1250_CS_AS"] = new(85, "Hungarian"),
            ["SQL_Icelandic_Pref_CP1_CI_AS"] = new(186, "Icelandic"),
            ["SQL_Latin1_General_CP1_CI_AI"] = new(54, "Latin1-General"),
            ["SQL_Latin1_General_CP1_CI_AS"] = new(52, "Latin1-General"),
            ["SQL_Latin1_General_CP1_CS_AS"] = new(51, "Latin1-General"),
            ["SQL_Latin1_General_CP1250_CI_AS"] = new(82, "Latin1-General"),
            ["SQL_Latin1_General_CP1250_CS_AS"] = new(81, "Latin1-General"),
            ["SQL_Latin1_General_CP1251_CI_AS"] = new(106, "Latin1-General"),
            ["SQL_Latin1_General_CP1251_CS_AS"] = new(105, "Latin1-General"),
            ["SQL_Latin1_General_CP1253_CI_AI"] = new(124, "Latin1-General"),
            ["SQL_Latin1_General_CP1253_CI_AS"] = new(114, "Latin1-General"),
            ["SQL_Latin1_General_CP1253_CS_AS"] = new(113, "Latin1-General"),
            ["SQL_Latin1_General_CP1254_CI_AS"] = new(130, "Turkish"),
            ["SQL_Latin1_General_CP1254_CS_AS"] = new(129, "Turkish"),
            ["SQL_Latin1_General_CP1255_CI_AS"] = new(138, "Latin1-General"),
            ["SQL_Latin1_General_CP1255_CS_AS"] = new(137, "Latin1-General"),
            ["SQL_Latin1_General_CP1256_CI_AS"] = new(146, "Latin1-General"),
            ["SQL_Latin1_General_CP1256_CS_AS"] = new(145, "Latin1-General"),
            ["SQL_Latin1_General_CP1257_CI_AS"] = new(154, "Latin1-General"),
            ["SQL_Latin1_General_CP1257_CS_AS"] = new(153, "Latin1-General"),
            ["SQL_Latin1_General_CP437_BIN"] = new(30, "Latin1-General"),
            ["SQL_Latin1_General_CP437_BIN2"] = new(30, "Latin1-General"),
            ["SQL_Latin1_General_CP437_CI_AI"] = new(34, "Latin1-General"),
            ["SQL_Latin1_General_CP437_CI_AS"] = new(32, "Latin1-General"),
            ["SQL_Latin1_General_CP437_CS_AS"] = new(31, "Latin1-General"),
            ["SQL_Latin1_General_CP850_BIN"] = new(40, "Latin1-General"),
            ["SQL_Latin1_General_CP850_BIN2"] = new(40, "Latin1-General"),
            ["SQL_Latin1_General_CP850_CI_AI"] = new(44, "Latin1-General"),
            ["SQL_Latin1_General_CP850_CI_AS"] = new(42, "Latin1-General"),
            ["SQL_Latin1_General_CP850_CS_AS"] = new(41, "Latin1-General"),
            ["SQL_Latin1_General_Pref_CP1_CI_AS"] = new(53, "Latin1-General"),
            ["SQL_Latin1_General_Pref_CP437_CI_AS"] = new(33, "Latin1-General"),
            ["SQL_Latin1_General_Pref_CP850_CI_AS"] = new(43, "Latin1-General"),
            ["SQL_Latvian_CP1257_CI_AS"] = new(158, "Latvian"),
            ["SQL_Latvian_CP1257_CS_AS"] = new(157, "Latvian"),
            ["SQL_Lithuanian_CP1257_CI_AS"] = new(160, "Lithuanian"),
            ["SQL_Lithuanian_CP1257_CS_AS"] = new(159, "Lithuanian"),
            ["SQL_MixDiction_CP1253_CS_AS"] = new(120, "Latin1-General"),
            ["SQL_Polish_CP1250_CI_AS"] = new(88, "Polish"),
            ["SQL_Polish_CP1250_CS_AS"] = new(87, "Polish"),
            ["SQL_Romanian_CP1250_CI_AS"] = new(90, "Romanian"),
            ["SQL_Romanian_CP1250_CS_AS"] = new(89, "Romanian"),
            ["SQL_Scandinavian_CP850_CI_AS"] = new(60, "Finnish-Swedish"),
            ["SQL_Scandinavian_CP850_CS_AS"] = new(59, "Finnish-Swedish"),
            ["SQL_Scandinavian_Pref_CP850_CI_AS"] = new(58, "Finnish-Swedish"),
            ["SQL_Slovak_CP1250_CI_AS"] = new(94, "Slovak"),
            ["SQL_Slovak_CP1250_CS_AS"] = new(93, "Slovak"),
            ["SQL_Slovenian_CP1250_CI_AS"] = new(96, "Slovenian"),
            ["SQL_Slovenian_CP1250_CS_AS"] = new(95, "Slovenian"),
            ["SQL_SwedishPhone_Pref_CP1_CI_AS"] = new(184, "Finnish-Swedish"),
            ["SQL_SwedishStd_Pref_CP1_CI_AS"] = new(185, "Finnish-Swedish"),
            ["SQL_Ukrainian_CP1251_CI_AS"] = new(108, "Ukrainian"),
            ["SQL_Ukrainian_CP1251_CS_AS"] = new(107, "Ukrainian"),
        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    // ===========================================================================
    // Tail-set catalog for non-SQL_* prefixes — probed against SQL Server 2025
    // on 2026-05-21 and grouped by tail-set signature. Across 89 non-SQL_*
    // prefixes only 9 distinct tail-sets appear; the parser validates a name
    // by looking up the prefix's pattern index and checking the suffix against
    // that pattern's tail set. SQL_* names validate against the per-name
    // <see cref="SqlServerSortOrders"/> table above.
    // ===========================================================================

    // Pattern 0 — 39 prefix(es), 50 tails. Prefixes: Assamese, Azeri_Cyrillic, Azeri_Latin, Bashkir, Bengali, Bosnian_Cyrillic, Bosnian_Latin, Breton, Chinese_Traditional_Bopomofo, Chinese_Traditional_Pinyin, Chinese_Traditional_Stroke_Count, Chinese_Traditional_Stroke_Order, Corsican, Danish_Greenlandic, Dari, Frisian, Khmer, Lao, Maltese, Maori, Mapudungan, Mohawk, Nepali, Norwegian, Pashto, Persian, Romansh, Sami_Norway, Sami_Sweden_Finland, Serbian_Cyrillic, Serbian_Latin, Tamazight, Tibetan, Turkmen, Uighur, Upper_Sorbian, Urdu, Welsh, Yakut
    private static readonly FrozenSet<string> Pattern0Tails = new[]
    {
        "_100_BIN",
        "_100_BIN2",
        "_100_CI_AI",
        "_100_CI_AI_KS",
        "_100_CI_AI_KS_SC",
        "_100_CI_AI_KS_SC_UTF8",
        "_100_CI_AI_KS_WS",
        "_100_CI_AI_KS_WS_SC",
        "_100_CI_AI_KS_WS_SC_UTF8",
        "_100_CI_AI_SC",
        "_100_CI_AI_SC_UTF8",
        "_100_CI_AI_WS",
        "_100_CI_AI_WS_SC",
        "_100_CI_AI_WS_SC_UTF8",
        "_100_CI_AS",
        "_100_CI_AS_KS",
        "_100_CI_AS_KS_SC",
        "_100_CI_AS_KS_SC_UTF8",
        "_100_CI_AS_KS_WS",
        "_100_CI_AS_KS_WS_SC",
        "_100_CI_AS_KS_WS_SC_UTF8",
        "_100_CI_AS_SC",
        "_100_CI_AS_SC_UTF8",
        "_100_CI_AS_WS",
        "_100_CI_AS_WS_SC",
        "_100_CI_AS_WS_SC_UTF8",
        "_100_CS_AI",
        "_100_CS_AI_KS",
        "_100_CS_AI_KS_SC",
        "_100_CS_AI_KS_SC_UTF8",
        "_100_CS_AI_KS_WS",
        "_100_CS_AI_KS_WS_SC",
        "_100_CS_AI_KS_WS_SC_UTF8",
        "_100_CS_AI_SC",
        "_100_CS_AI_SC_UTF8",
        "_100_CS_AI_WS",
        "_100_CS_AI_WS_SC",
        "_100_CS_AI_WS_SC_UTF8",
        "_100_CS_AS",
        "_100_CS_AS_KS",
        "_100_CS_AS_KS_SC",
        "_100_CS_AS_KS_SC_UTF8",
        "_100_CS_AS_KS_WS",
        "_100_CS_AS_KS_WS_SC",
        "_100_CS_AS_KS_WS_SC_UTF8",
        "_100_CS_AS_SC",
        "_100_CS_AS_SC_UTF8",
        "_100_CS_AS_WS",
        "_100_CS_AS_WS_SC",
        "_100_CS_AS_WS_SC_UTF8",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 1 — 27 prefix(es), 68 tails. Prefixes: Albanian, Arabic, Croatian, Cyrillic_General, Czech, Estonian, Finnish_Swedish, French, Georgian_Modern_Sort, German_PhoneBook, Greek, Hebrew, Hungarian, Hungarian_Technical, Icelandic, Latvian, Lithuanian, Modern_Spanish, Polish, Romanian, Slovak, Slovenian, Thai, Traditional_Spanish, Turkish, Ukrainian, Vietnamese
    private static readonly FrozenSet<string> Pattern1Tails = new[]
    {
        "_100_BIN",
        "_100_BIN2",
        "_100_CI_AI",
        "_100_CI_AI_KS",
        "_100_CI_AI_KS_SC",
        "_100_CI_AI_KS_SC_UTF8",
        "_100_CI_AI_KS_WS",
        "_100_CI_AI_KS_WS_SC",
        "_100_CI_AI_KS_WS_SC_UTF8",
        "_100_CI_AI_SC",
        "_100_CI_AI_SC_UTF8",
        "_100_CI_AI_WS",
        "_100_CI_AI_WS_SC",
        "_100_CI_AI_WS_SC_UTF8",
        "_100_CI_AS",
        "_100_CI_AS_KS",
        "_100_CI_AS_KS_SC",
        "_100_CI_AS_KS_SC_UTF8",
        "_100_CI_AS_KS_WS",
        "_100_CI_AS_KS_WS_SC",
        "_100_CI_AS_KS_WS_SC_UTF8",
        "_100_CI_AS_SC",
        "_100_CI_AS_SC_UTF8",
        "_100_CI_AS_WS",
        "_100_CI_AS_WS_SC",
        "_100_CI_AS_WS_SC_UTF8",
        "_100_CS_AI",
        "_100_CS_AI_KS",
        "_100_CS_AI_KS_SC",
        "_100_CS_AI_KS_SC_UTF8",
        "_100_CS_AI_KS_WS",
        "_100_CS_AI_KS_WS_SC",
        "_100_CS_AI_KS_WS_SC_UTF8",
        "_100_CS_AI_SC",
        "_100_CS_AI_SC_UTF8",
        "_100_CS_AI_WS",
        "_100_CS_AI_WS_SC",
        "_100_CS_AI_WS_SC_UTF8",
        "_100_CS_AS",
        "_100_CS_AS_KS",
        "_100_CS_AS_KS_SC",
        "_100_CS_AS_KS_SC_UTF8",
        "_100_CS_AS_KS_WS",
        "_100_CS_AS_KS_WS_SC",
        "_100_CS_AS_KS_WS_SC_UTF8",
        "_100_CS_AS_SC",
        "_100_CS_AS_SC_UTF8",
        "_100_CS_AS_WS",
        "_100_CS_AS_WS_SC",
        "_100_CS_AS_WS_SC_UTF8",
        "_BIN",
        "_BIN2",
        "_CI_AI",
        "_CI_AI_KS",
        "_CI_AI_KS_WS",
        "_CI_AI_WS",
        "_CI_AS",
        "_CI_AS_KS",
        "_CI_AS_KS_WS",
        "_CI_AS_WS",
        "_CS_AI",
        "_CS_AI_KS",
        "_CS_AI_KS_WS",
        "_CS_AI_WS",
        "_CS_AS",
        "_CS_AS_KS",
        "_CS_AS_KS_WS",
        "_CS_AS_WS",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 2 — 8 prefix(es), 100 tails. Prefixes: Divehi, Indic_General, Kazakh, Korean, Macedonian_FYROM, Syriac, Tatar, Uzbek_Latin
    private static readonly FrozenSet<string> Pattern2Tails = new[]
    {
        "_100_BIN",
        "_100_BIN2",
        "_100_CI_AI",
        "_100_CI_AI_KS",
        "_100_CI_AI_KS_SC",
        "_100_CI_AI_KS_SC_UTF8",
        "_100_CI_AI_KS_WS",
        "_100_CI_AI_KS_WS_SC",
        "_100_CI_AI_KS_WS_SC_UTF8",
        "_100_CI_AI_SC",
        "_100_CI_AI_SC_UTF8",
        "_100_CI_AI_WS",
        "_100_CI_AI_WS_SC",
        "_100_CI_AI_WS_SC_UTF8",
        "_100_CI_AS",
        "_100_CI_AS_KS",
        "_100_CI_AS_KS_SC",
        "_100_CI_AS_KS_SC_UTF8",
        "_100_CI_AS_KS_WS",
        "_100_CI_AS_KS_WS_SC",
        "_100_CI_AS_KS_WS_SC_UTF8",
        "_100_CI_AS_SC",
        "_100_CI_AS_SC_UTF8",
        "_100_CI_AS_WS",
        "_100_CI_AS_WS_SC",
        "_100_CI_AS_WS_SC_UTF8",
        "_100_CS_AI",
        "_100_CS_AI_KS",
        "_100_CS_AI_KS_SC",
        "_100_CS_AI_KS_SC_UTF8",
        "_100_CS_AI_KS_WS",
        "_100_CS_AI_KS_WS_SC",
        "_100_CS_AI_KS_WS_SC_UTF8",
        "_100_CS_AI_SC",
        "_100_CS_AI_SC_UTF8",
        "_100_CS_AI_WS",
        "_100_CS_AI_WS_SC",
        "_100_CS_AI_WS_SC_UTF8",
        "_100_CS_AS",
        "_100_CS_AS_KS",
        "_100_CS_AS_KS_SC",
        "_100_CS_AS_KS_SC_UTF8",
        "_100_CS_AS_KS_WS",
        "_100_CS_AS_KS_WS_SC",
        "_100_CS_AS_KS_WS_SC_UTF8",
        "_100_CS_AS_SC",
        "_100_CS_AS_SC_UTF8",
        "_100_CS_AS_WS",
        "_100_CS_AS_WS_SC",
        "_100_CS_AS_WS_SC_UTF8",
        "_90_BIN",
        "_90_BIN2",
        "_90_CI_AI",
        "_90_CI_AI_KS",
        "_90_CI_AI_KS_SC",
        "_90_CI_AI_KS_SC_UTF8",
        "_90_CI_AI_KS_WS",
        "_90_CI_AI_KS_WS_SC",
        "_90_CI_AI_KS_WS_SC_UTF8",
        "_90_CI_AI_SC",
        "_90_CI_AI_SC_UTF8",
        "_90_CI_AI_WS",
        "_90_CI_AI_WS_SC",
        "_90_CI_AI_WS_SC_UTF8",
        "_90_CI_AS",
        "_90_CI_AS_KS",
        "_90_CI_AS_KS_SC",
        "_90_CI_AS_KS_SC_UTF8",
        "_90_CI_AS_KS_WS",
        "_90_CI_AS_KS_WS_SC",
        "_90_CI_AS_KS_WS_SC_UTF8",
        "_90_CI_AS_SC",
        "_90_CI_AS_SC_UTF8",
        "_90_CI_AS_WS",
        "_90_CI_AS_WS_SC",
        "_90_CI_AS_WS_SC_UTF8",
        "_90_CS_AI",
        "_90_CS_AI_KS",
        "_90_CS_AI_KS_SC",
        "_90_CS_AI_KS_SC_UTF8",
        "_90_CS_AI_KS_WS",
        "_90_CS_AI_KS_WS_SC",
        "_90_CS_AI_KS_WS_SC_UTF8",
        "_90_CS_AI_SC",
        "_90_CS_AI_SC_UTF8",
        "_90_CS_AI_WS",
        "_90_CS_AI_WS_SC",
        "_90_CS_AI_WS_SC_UTF8",
        "_90_CS_AS",
        "_90_CS_AS_KS",
        "_90_CS_AS_KS_SC",
        "_90_CS_AS_KS_SC_UTF8",
        "_90_CS_AS_KS_WS",
        "_90_CS_AS_KS_WS_SC",
        "_90_CS_AS_KS_WS_SC_UTF8",
        "_90_CS_AS_SC",
        "_90_CS_AS_SC_UTF8",
        "_90_CS_AS_WS",
        "_90_CS_AS_WS_SC",
        "_90_CS_AS_WS_SC_UTF8",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 3 — 5 prefix(es), 68 tails. Prefixes: Chinese_PRC, Chinese_PRC_Stroke, Chinese_Taiwan_Bopomofo, Chinese_Taiwan_Stroke, Japanese
    private static readonly FrozenSet<string> Pattern3Tails = new[]
    {
        "_90_BIN",
        "_90_BIN2",
        "_90_CI_AI",
        "_90_CI_AI_KS",
        "_90_CI_AI_KS_SC",
        "_90_CI_AI_KS_SC_UTF8",
        "_90_CI_AI_KS_WS",
        "_90_CI_AI_KS_WS_SC",
        "_90_CI_AI_KS_WS_SC_UTF8",
        "_90_CI_AI_SC",
        "_90_CI_AI_SC_UTF8",
        "_90_CI_AI_WS",
        "_90_CI_AI_WS_SC",
        "_90_CI_AI_WS_SC_UTF8",
        "_90_CI_AS",
        "_90_CI_AS_KS",
        "_90_CI_AS_KS_SC",
        "_90_CI_AS_KS_SC_UTF8",
        "_90_CI_AS_KS_WS",
        "_90_CI_AS_KS_WS_SC",
        "_90_CI_AS_KS_WS_SC_UTF8",
        "_90_CI_AS_SC",
        "_90_CI_AS_SC_UTF8",
        "_90_CI_AS_WS",
        "_90_CI_AS_WS_SC",
        "_90_CI_AS_WS_SC_UTF8",
        "_90_CS_AI",
        "_90_CS_AI_KS",
        "_90_CS_AI_KS_SC",
        "_90_CS_AI_KS_SC_UTF8",
        "_90_CS_AI_KS_WS",
        "_90_CS_AI_KS_WS_SC",
        "_90_CS_AI_KS_WS_SC_UTF8",
        "_90_CS_AI_SC",
        "_90_CS_AI_SC_UTF8",
        "_90_CS_AI_WS",
        "_90_CS_AI_WS_SC",
        "_90_CS_AI_WS_SC_UTF8",
        "_90_CS_AS",
        "_90_CS_AS_KS",
        "_90_CS_AS_KS_SC",
        "_90_CS_AS_KS_SC_UTF8",
        "_90_CS_AS_KS_WS",
        "_90_CS_AS_KS_WS_SC",
        "_90_CS_AS_KS_WS_SC_UTF8",
        "_90_CS_AS_SC",
        "_90_CS_AS_SC_UTF8",
        "_90_CS_AS_WS",
        "_90_CS_AS_WS_SC",
        "_90_CS_AS_WS_SC_UTF8",
        "_BIN",
        "_BIN2",
        "_CI_AI",
        "_CI_AI_KS",
        "_CI_AI_KS_WS",
        "_CI_AI_WS",
        "_CI_AS",
        "_CI_AS_KS",
        "_CI_AS_KS_WS",
        "_CI_AS_WS",
        "_CS_AI",
        "_CS_AI_KS",
        "_CS_AI_KS_WS",
        "_CS_AI_WS",
        "_CS_AS",
        "_CS_AS_KS",
        "_CS_AS_KS_WS",
        "_CS_AS_WS",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 4 — 3 prefix(es), 18 tails. Prefixes: Danish_Norwegian, Japanese_Unicode, Korean_Wansung
    private static readonly FrozenSet<string> Pattern4Tails = new[]
    {
        "_BIN",
        "_BIN2",
        "_CI_AI",
        "_CI_AI_KS",
        "_CI_AI_KS_WS",
        "_CI_AI_WS",
        "_CI_AS",
        "_CI_AS_KS",
        "_CI_AS_KS_WS",
        "_CI_AS_WS",
        "_CS_AI",
        "_CS_AI_KS",
        "_CS_AI_KS_WS",
        "_CS_AI_WS",
        "_CS_AS",
        "_CS_AS_KS",
        "_CS_AS_KS_WS",
        "_CS_AS_WS",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 5 — 2 prefix(es), 66 tails. Prefixes: Chinese_Simplified_Pinyin, Chinese_Simplified_Stroke_Order
    private static readonly FrozenSet<string> Pattern5Tails = new[]
    {
        "_100_BIN",
        "_100_BIN2",
        "_100_CI_AI",
        "_100_CI_AI_KS",
        "_100_CI_AI_KS_SC",
        "_100_CI_AI_KS_SC_UTF8",
        "_100_CI_AI_KS_WS",
        "_100_CI_AI_KS_WS_SC",
        "_100_CI_AI_KS_WS_SC_UTF8",
        "_100_CI_AI_SC",
        "_100_CI_AI_SC_UTF8",
        "_100_CI_AI_WS",
        "_100_CI_AI_WS_SC",
        "_100_CI_AI_WS_SC_UTF8",
        "_100_CI_AS",
        "_100_CI_AS_KS",
        "_100_CI_AS_KS_SC",
        "_100_CI_AS_KS_SC_UTF8",
        "_100_CI_AS_KS_WS",
        "_100_CI_AS_KS_WS_SC",
        "_100_CI_AS_KS_WS_SC_UTF8",
        "_100_CI_AS_SC",
        "_100_CI_AS_SC_UTF8",
        "_100_CI_AS_WS",
        "_100_CI_AS_WS_SC",
        "_100_CI_AS_WS_SC_UTF8",
        "_100_CS_AI",
        "_100_CS_AI_KS",
        "_100_CS_AI_KS_SC",
        "_100_CS_AI_KS_SC_UTF8",
        "_100_CS_AI_KS_WS",
        "_100_CS_AI_KS_WS_SC",
        "_100_CS_AI_KS_WS_SC_UTF8",
        "_100_CS_AI_SC",
        "_100_CS_AI_SC_UTF8",
        "_100_CS_AI_WS",
        "_100_CS_AI_WS_SC",
        "_100_CS_AI_WS_SC_UTF8",
        "_100_CS_AS",
        "_100_CS_AS_KS",
        "_100_CS_AS_KS_SC",
        "_100_CS_AS_KS_SC_UTF8",
        "_100_CS_AS_KS_WS",
        "_100_CS_AS_KS_WS_SC",
        "_100_CS_AS_KS_WS_SC_UTF8",
        "_100_CS_AS_SC",
        "_100_CS_AS_SC_UTF8",
        "_100_CS_AS_WS",
        "_100_CS_AS_WS_SC",
        "_100_CS_AS_WS_SC_UTF8",
        "_160_CI_AI_KS_SC_UTF8",
        "_160_CI_AI_KS_WS_SC_UTF8",
        "_160_CI_AI_SC_UTF8",
        "_160_CI_AI_WS_SC_UTF8",
        "_160_CI_AS_KS_SC_UTF8",
        "_160_CI_AS_KS_WS_SC_UTF8",
        "_160_CI_AS_SC_UTF8",
        "_160_CI_AS_WS_SC_UTF8",
        "_160_CS_AI_KS_SC_UTF8",
        "_160_CS_AI_KS_WS_SC_UTF8",
        "_160_CS_AI_SC_UTF8",
        "_160_CS_AI_WS_SC_UTF8",
        "_160_CS_AS_KS_SC_UTF8",
        "_160_CS_AS_KS_WS_SC_UTF8",
        "_160_CS_AS_SC_UTF8",
        "_160_CS_AS_WS_SC_UTF8",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 6 — 2 prefix(es), 116 tails. Prefixes: Japanese_Bushu_Kakusu, Japanese_XJIS
    private static readonly FrozenSet<string> Pattern6Tails = new[]
    {
        "_100_BIN",
        "_100_BIN2",
        "_100_CI_AI",
        "_100_CI_AI_KS",
        "_100_CI_AI_KS_SC",
        "_100_CI_AI_KS_SC_UTF8",
        "_100_CI_AI_KS_WS",
        "_100_CI_AI_KS_WS_SC",
        "_100_CI_AI_KS_WS_SC_UTF8",
        "_100_CI_AI_SC",
        "_100_CI_AI_SC_UTF8",
        "_100_CI_AI_WS",
        "_100_CI_AI_WS_SC",
        "_100_CI_AI_WS_SC_UTF8",
        "_100_CI_AS",
        "_100_CI_AS_KS",
        "_100_CI_AS_KS_SC",
        "_100_CI_AS_KS_SC_UTF8",
        "_100_CI_AS_KS_WS",
        "_100_CI_AS_KS_WS_SC",
        "_100_CI_AS_KS_WS_SC_UTF8",
        "_100_CI_AS_SC",
        "_100_CI_AS_SC_UTF8",
        "_100_CI_AS_WS",
        "_100_CI_AS_WS_SC",
        "_100_CI_AS_WS_SC_UTF8",
        "_100_CS_AI",
        "_100_CS_AI_KS",
        "_100_CS_AI_KS_SC",
        "_100_CS_AI_KS_SC_UTF8",
        "_100_CS_AI_KS_WS",
        "_100_CS_AI_KS_WS_SC",
        "_100_CS_AI_KS_WS_SC_UTF8",
        "_100_CS_AI_SC",
        "_100_CS_AI_SC_UTF8",
        "_100_CS_AI_WS",
        "_100_CS_AI_WS_SC",
        "_100_CS_AI_WS_SC_UTF8",
        "_100_CS_AS",
        "_100_CS_AS_KS",
        "_100_CS_AS_KS_SC",
        "_100_CS_AS_KS_SC_UTF8",
        "_100_CS_AS_KS_WS",
        "_100_CS_AS_KS_WS_SC",
        "_100_CS_AS_KS_WS_SC_UTF8",
        "_100_CS_AS_SC",
        "_100_CS_AS_SC_UTF8",
        "_100_CS_AS_WS",
        "_100_CS_AS_WS_SC",
        "_100_CS_AS_WS_SC_UTF8",
        "_140_BIN",
        "_140_BIN2",
        "_140_CI_AI",
        "_140_CI_AI_KS",
        "_140_CI_AI_KS_UTF8",
        "_140_CI_AI_KS_VSS",
        "_140_CI_AI_KS_VSS_UTF8",
        "_140_CI_AI_KS_WS",
        "_140_CI_AI_KS_WS_UTF8",
        "_140_CI_AI_KS_WS_VSS",
        "_140_CI_AI_KS_WS_VSS_UTF8",
        "_140_CI_AI_UTF8",
        "_140_CI_AI_VSS",
        "_140_CI_AI_VSS_UTF8",
        "_140_CI_AI_WS",
        "_140_CI_AI_WS_UTF8",
        "_140_CI_AI_WS_VSS",
        "_140_CI_AI_WS_VSS_UTF8",
        "_140_CI_AS",
        "_140_CI_AS_KS",
        "_140_CI_AS_KS_UTF8",
        "_140_CI_AS_KS_VSS",
        "_140_CI_AS_KS_VSS_UTF8",
        "_140_CI_AS_KS_WS",
        "_140_CI_AS_KS_WS_UTF8",
        "_140_CI_AS_KS_WS_VSS",
        "_140_CI_AS_KS_WS_VSS_UTF8",
        "_140_CI_AS_UTF8",
        "_140_CI_AS_VSS",
        "_140_CI_AS_VSS_UTF8",
        "_140_CI_AS_WS",
        "_140_CI_AS_WS_UTF8",
        "_140_CI_AS_WS_VSS",
        "_140_CI_AS_WS_VSS_UTF8",
        "_140_CS_AI",
        "_140_CS_AI_KS",
        "_140_CS_AI_KS_UTF8",
        "_140_CS_AI_KS_VSS",
        "_140_CS_AI_KS_VSS_UTF8",
        "_140_CS_AI_KS_WS",
        "_140_CS_AI_KS_WS_UTF8",
        "_140_CS_AI_KS_WS_VSS",
        "_140_CS_AI_KS_WS_VSS_UTF8",
        "_140_CS_AI_UTF8",
        "_140_CS_AI_VSS",
        "_140_CS_AI_VSS_UTF8",
        "_140_CS_AI_WS",
        "_140_CS_AI_WS_UTF8",
        "_140_CS_AI_WS_VSS",
        "_140_CS_AI_WS_VSS_UTF8",
        "_140_CS_AS",
        "_140_CS_AS_KS",
        "_140_CS_AS_KS_UTF8",
        "_140_CS_AS_KS_VSS",
        "_140_CS_AS_KS_VSS_UTF8",
        "_140_CS_AS_KS_WS",
        "_140_CS_AS_KS_WS_UTF8",
        "_140_CS_AS_KS_WS_VSS",
        "_140_CS_AS_KS_WS_VSS_UTF8",
        "_140_CS_AS_UTF8",
        "_140_CS_AS_VSS",
        "_140_CS_AS_VSS_UTF8",
        "_140_CS_AS_WS",
        "_140_CS_AS_WS_UTF8",
        "_140_CS_AS_WS_VSS",
        "_140_CS_AS_WS_VSS_UTF8",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 7 — 1 prefix(es), 50 tails. Prefixes: Chinese_Hong_Kong_Stroke
    private static readonly FrozenSet<string> Pattern7Tails = new[]
    {
        "_90_BIN",
        "_90_BIN2",
        "_90_CI_AI",
        "_90_CI_AI_KS",
        "_90_CI_AI_KS_SC",
        "_90_CI_AI_KS_SC_UTF8",
        "_90_CI_AI_KS_WS",
        "_90_CI_AI_KS_WS_SC",
        "_90_CI_AI_KS_WS_SC_UTF8",
        "_90_CI_AI_SC",
        "_90_CI_AI_SC_UTF8",
        "_90_CI_AI_WS",
        "_90_CI_AI_WS_SC",
        "_90_CI_AI_WS_SC_UTF8",
        "_90_CI_AS",
        "_90_CI_AS_KS",
        "_90_CI_AS_KS_SC",
        "_90_CI_AS_KS_SC_UTF8",
        "_90_CI_AS_KS_WS",
        "_90_CI_AS_KS_WS_SC",
        "_90_CI_AS_KS_WS_SC_UTF8",
        "_90_CI_AS_SC",
        "_90_CI_AS_SC_UTF8",
        "_90_CI_AS_WS",
        "_90_CI_AS_WS_SC",
        "_90_CI_AS_WS_SC_UTF8",
        "_90_CS_AI",
        "_90_CS_AI_KS",
        "_90_CS_AI_KS_SC",
        "_90_CS_AI_KS_SC_UTF8",
        "_90_CS_AI_KS_WS",
        "_90_CS_AI_KS_WS_SC",
        "_90_CS_AI_KS_WS_SC_UTF8",
        "_90_CS_AI_SC",
        "_90_CS_AI_SC_UTF8",
        "_90_CS_AI_WS",
        "_90_CS_AI_WS_SC",
        "_90_CS_AI_WS_SC_UTF8",
        "_90_CS_AS",
        "_90_CS_AS_KS",
        "_90_CS_AS_KS_SC",
        "_90_CS_AS_KS_SC_UTF8",
        "_90_CS_AS_KS_WS",
        "_90_CS_AS_KS_WS_SC",
        "_90_CS_AS_KS_WS_SC_UTF8",
        "_90_CS_AS_SC",
        "_90_CS_AS_SC_UTF8",
        "_90_CS_AS_WS",
        "_90_CS_AS_WS_SC",
        "_90_CS_AS_WS_SC_UTF8",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Pattern 8 — 1 prefix(es), 69 tails. Prefixes: Latin1_General
    private static readonly FrozenSet<string> Pattern8Tails = new[]
    {
        "_100_BIN",
        "_100_BIN2",
        "_100_BIN2_UTF8",
        "_100_CI_AI",
        "_100_CI_AI_KS",
        "_100_CI_AI_KS_SC",
        "_100_CI_AI_KS_SC_UTF8",
        "_100_CI_AI_KS_WS",
        "_100_CI_AI_KS_WS_SC",
        "_100_CI_AI_KS_WS_SC_UTF8",
        "_100_CI_AI_SC",
        "_100_CI_AI_SC_UTF8",
        "_100_CI_AI_WS",
        "_100_CI_AI_WS_SC",
        "_100_CI_AI_WS_SC_UTF8",
        "_100_CI_AS",
        "_100_CI_AS_KS",
        "_100_CI_AS_KS_SC",
        "_100_CI_AS_KS_SC_UTF8",
        "_100_CI_AS_KS_WS",
        "_100_CI_AS_KS_WS_SC",
        "_100_CI_AS_KS_WS_SC_UTF8",
        "_100_CI_AS_SC",
        "_100_CI_AS_SC_UTF8",
        "_100_CI_AS_WS",
        "_100_CI_AS_WS_SC",
        "_100_CI_AS_WS_SC_UTF8",
        "_100_CS_AI",
        "_100_CS_AI_KS",
        "_100_CS_AI_KS_SC",
        "_100_CS_AI_KS_SC_UTF8",
        "_100_CS_AI_KS_WS",
        "_100_CS_AI_KS_WS_SC",
        "_100_CS_AI_KS_WS_SC_UTF8",
        "_100_CS_AI_SC",
        "_100_CS_AI_SC_UTF8",
        "_100_CS_AI_WS",
        "_100_CS_AI_WS_SC",
        "_100_CS_AI_WS_SC_UTF8",
        "_100_CS_AS",
        "_100_CS_AS_KS",
        "_100_CS_AS_KS_SC",
        "_100_CS_AS_KS_SC_UTF8",
        "_100_CS_AS_KS_WS",
        "_100_CS_AS_KS_WS_SC",
        "_100_CS_AS_KS_WS_SC_UTF8",
        "_100_CS_AS_SC",
        "_100_CS_AS_SC_UTF8",
        "_100_CS_AS_WS",
        "_100_CS_AS_WS_SC",
        "_100_CS_AS_WS_SC_UTF8",
        "_BIN",
        "_BIN2",
        "_CI_AI",
        "_CI_AI_KS",
        "_CI_AI_KS_WS",
        "_CI_AI_WS",
        "_CI_AS",
        "_CI_AS_KS",
        "_CI_AS_KS_WS",
        "_CI_AS_WS",
        "_CS_AI",
        "_CS_AI_KS",
        "_CS_AI_KS_WS",
        "_CS_AI_WS",
        "_CS_AS",
        "_CS_AS_KS",
        "_CS_AS_KS_WS",
        "_CS_AS_WS",
    }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    // Prefix → tail-pattern index (88 entries).
    private static readonly FrozenDictionary<string, int> PrefixToPattern =
        new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
        {
            ["Assamese"] = 0,
            ["Azeri_Cyrillic"] = 0,
            ["Azeri_Latin"] = 0,
            ["Bashkir"] = 0,
            ["Bengali"] = 0,
            ["Bosnian_Cyrillic"] = 0,
            ["Bosnian_Latin"] = 0,
            ["Breton"] = 0,
            ["Chinese_Traditional_Bopomofo"] = 0,
            ["Chinese_Traditional_Pinyin"] = 0,
            ["Chinese_Traditional_Stroke_Count"] = 0,
            ["Chinese_Traditional_Stroke_Order"] = 0,
            ["Corsican"] = 0,
            ["Danish_Greenlandic"] = 0,
            ["Dari"] = 0,
            ["Frisian"] = 0,
            ["Khmer"] = 0,
            ["Lao"] = 0,
            ["Maltese"] = 0,
            ["Maori"] = 0,
            ["Mapudungan"] = 0,
            ["Mohawk"] = 0,
            ["Nepali"] = 0,
            ["Norwegian"] = 0,
            ["Pashto"] = 0,
            ["Persian"] = 0,
            ["Romansh"] = 0,
            ["Sami_Norway"] = 0,
            ["Sami_Sweden_Finland"] = 0,
            ["Serbian_Cyrillic"] = 0,
            ["Serbian_Latin"] = 0,
            ["Tamazight"] = 0,
            ["Tibetan"] = 0,
            ["Turkmen"] = 0,
            ["Uighur"] = 0,
            ["Upper_Sorbian"] = 0,
            ["Urdu"] = 0,
            ["Welsh"] = 0,
            ["Yakut"] = 0,
            ["Albanian"] = 1,
            ["Arabic"] = 1,
            ["Croatian"] = 1,
            ["Cyrillic_General"] = 1,
            ["Czech"] = 1,
            ["Estonian"] = 1,
            ["Finnish_Swedish"] = 1,
            ["French"] = 1,
            ["Georgian_Modern_Sort"] = 1,
            ["German_PhoneBook"] = 1,
            ["Greek"] = 1,
            ["Hebrew"] = 1,
            ["Hungarian"] = 1,
            ["Hungarian_Technical"] = 1,
            ["Icelandic"] = 1,
            ["Latvian"] = 1,
            ["Lithuanian"] = 1,
            ["Modern_Spanish"] = 1,
            ["Polish"] = 1,
            ["Romanian"] = 1,
            ["Slovak"] = 1,
            ["Slovenian"] = 1,
            ["Thai"] = 1,
            ["Traditional_Spanish"] = 1,
            ["Turkish"] = 1,
            ["Ukrainian"] = 1,
            ["Vietnamese"] = 1,
            ["Divehi"] = 2,
            ["Indic_General"] = 2,
            ["Kazakh"] = 2,
            ["Korean"] = 2,
            ["Macedonian_FYROM"] = 2,
            ["Syriac"] = 2,
            ["Tatar"] = 2,
            ["Uzbek_Latin"] = 2,
            ["Chinese_PRC"] = 3,
            ["Chinese_PRC_Stroke"] = 3,
            ["Chinese_Taiwan_Bopomofo"] = 3,
            ["Chinese_Taiwan_Stroke"] = 3,
            ["Japanese"] = 3,
            ["Danish_Norwegian"] = 4,
            ["Japanese_Unicode"] = 4,
            ["Korean_Wansung"] = 4,
            ["Chinese_Simplified_Pinyin"] = 5,
            ["Chinese_Simplified_Stroke_Order"] = 5,
            ["Japanese_Bushu_Kakusu"] = 6,
            ["Japanese_XJIS"] = 6,
            ["Chinese_Hong_Kong_Stroke"] = 7,
            ["Latin1_General"] = 8,
        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    private static FrozenSet<string> GetPatternTails(int idx) => idx switch
    {
        0 => Pattern0Tails,
        1 => Pattern1Tails,
        2 => Pattern2Tails,
        3 => Pattern3Tails,
        4 => Pattern4Tails,
        5 => Pattern5Tails,
        6 => Pattern6Tails,
        7 => Pattern7Tails,
        8 => Pattern8Tails,
        _ => [],
    };
}
