<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>1591</NoWarn>
    <RootNamespace>SqlServerSimulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.SqlServer.Types" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqlServerSimulator\SqlServerSimulator.csproj" />
  </ItemGroup>

</Project>
