using System.Globalization;
using System.Text;
using SqlServerSimulator.Storage;

namespace SqlServerSimulator;

/// <summary>
/// SQL Server's collation-precedence rank. Used by the expression layer to
/// decide which collation wins when two string operands meet; mismatched
/// peers raise <c>Msg 468</c> / <c>Msg 457</c>.
/// </summary>
/// <remarks>
/// Real SQL Server defines additional ranks (<c>Coercible-default</c>,
/// <c>Implicit X</c>, <c>Explicit X</c>, <c>No-collation</c>); the simulator
/// collapses them to the three that drive observable behavior. Hierarchy:
/// <see cref="Explicit"/> beats <see cref="Implicit"/> beats
/// <see cref="CoercibleDefault"/>; peers with the same rank but different
/// collations raise the conflict error.
/// </remarks>
internal enum Coercibility : byte
{
    /// <summary>Literal, parameter, system-function result, CAST of a coercible-default source. Yields to <see cref="Implicit"/> / <see cref="Explicit"/> peers.</summary>
    CoercibleDefault = 0,

    /// <summary>Column reference, CAST of a column, computed-column expression. Two implicits with different collations raise Msg 468 / 457.</summary>
    Implicit = 1,

    /// <summary>Explicit <c>COLLATE</c> postfix. Beats both lower ranks; two explicits with different collations raise Msg 468 / 457.</summary>
    Explicit = 2,
}

/// <summary>
/// The SQL Server equivalent to .NET's <see cref="IComparer{T}"/> for strings.
/// Concrete subclasses are constructed by the parser
/// (<see cref="TryParse(string, out Collation?)"/>) from the grammatical
/// shape of the collation name; hand-tuned bespoke bodies can be registered
/// via the override slot for names whose behavior diverges from the
/// grammar-derived default. See <c>docs/claude/collations.md</c> for the
/// catalog, parser, and override-slot details.
/// </summary>
internal abstract partial class Collation : IComparer<string>, IEqualityComparer<string>
{
    private protected Collation()
    {
    }

    public abstract string Name { get; }

    /// <summary>
    /// Human-readable description of this collation — matches the format
    /// emitted by <c>sys.fn_helpcollations()</c>. Generated by
    /// <see cref="BuildDescription"/> for parser-derived instances;
    /// override-registry entries supply their own text.
    /// </summary>
    public abstract string Description { get; }

    /// <summary>
    /// True when the collation name carries the <c>_CS_</c> or <c>_BIN</c>
    /// marker — i.e. case differences are significant. Consulted by
    /// <c>LIKE</c>'s regex builder to decide whether to set
    /// <c>System.Text.RegularExpressions.RegexOptions.IgnoreCase</c>.
    /// Other string ops (sort, equality, hash) honor the collation
    /// directly through <see cref="Compare"/> / <see cref="Equals"/> /
    /// <see cref="GetHashCode"/> via the column type's pinned collation.
    /// </summary>
    public virtual bool CaseSensitive => false;

    /// <summary>
    /// The simulator's hardcoded baseline collation —
    /// <c>SQL_Latin1_General_CP1_CI_AS</c>. Resolved once via
    /// <see cref="TryGet"/>. Used as the seed for new
    /// <see cref="Database.Collation"/> instances, as the fallback for
    /// string-typed values whose <see cref="SqlType.Collation"/> is
    /// <see langword="null"/>, and as the default for the storage-layer
    /// <see cref="VarcharSqlType"/> / <see cref="NVarcharSqlType"/> /
    /// <see cref="CharSqlType"/> / <see cref="NCharSqlType"/> singletons.
    /// Identifier-resolution sites should route through
    /// <see cref="Database.Collation"/> (which defaults here but may
    /// diverge under <c>ALTER DATABASE COLLATE</c>); only sites that
    /// genuinely need "the simulator's baseline regardless of database"
    /// belong on this property.
    /// </summary>
    internal static Collation Default => defaultLazy.Value;

    // <see cref="Lazy{T}"/> wrapper defers the <see cref="TryGet"/> call
    // until first access — the alternative (eager field initialization)
    // races the parser-state fields across partial-class file boundaries
    // and the textual-order guarantee for static-field initializers
    // doesn't cross those.
    private static readonly Lazy<Collation> defaultLazy =
        new(() => TryGet("SQL_Latin1_General_CP1_CI_AS")!);

    /// <summary>
    /// SQL Server's collation-coercibility resolution for two operands.
    /// Returns the winning <see cref="Collation"/> and <see cref="Coercibility"/>
    /// when the pair is resolvable; <see langword="null"/> when both
    /// operands have the same rank but different collations (the caller is
    /// expected to raise Msg 468 / Msg 457 with operator context).
    /// </summary>
    /// <remarks>
    /// <para>Hierarchy: <see cref="Coercibility.Explicit"/> beats
    /// <see cref="Coercibility.Implicit"/> beats
    /// <see cref="Coercibility.CoercibleDefault"/>. Mismatched higher rank
    /// wins regardless of the lower-rank operand's collation. Equal-rank
    /// peers must share a collation; different collations at the same rank
    /// are unresolvable.</para>
    /// <para>Non-string operands return <see langword="null"/> for
    /// <c>Collation</c> on the SqlType, which collapses to the default
    /// collation under this resolution (a non-string operand is
    /// coercible-default by definition, and there's nothing to conflict
    /// with).</para>
    /// </remarks>
    internal static (Collation Collation, Coercibility Coercibility)? Resolve(SqlType a, SqlType b)
    {
        var ca = a.Coercibility;
        var cb = b.Coercibility;
        if (ca > cb)
            return (a.Collation ?? Default, ca);
        if (cb > ca)
            return (b.Collation ?? Default, cb);
        var aCol = a.Collation ?? Default;
        var bCol = b.Collation ?? Default;
        return StringComparer.OrdinalIgnoreCase.Equals(aCol.Name, bCol.Name) ? (aCol, ca) : null;
    }

    public abstract int Compare(string? x, string? y);

    public abstract bool Equals(string? x, string? y);

    public abstract int GetHashCode(string obj);

    /// <summary>
    /// Returns the comparer body to use when this collation is pinned on
    /// a varchar / char column. The base implementation returns
    /// <see langword="this"/>; binary collations override to return a
    /// CP1252- or UTF-8-byte-aware sibling because varchar BIN/BIN2 in
    /// real SQL Server byte-compares the stored encoding rather than
    /// UTF-16 code points. Called by <see cref="VarcharSqlType.WithCollation"/>
    /// and <see cref="CharSqlType.WithCollation"/>; nvarchar / nchar
    /// don't substitute (UTF-16 storage already matches the UTF-16
    /// code-unit-order body).
    /// </summary>
    internal virtual Collation ForVarcharStorage() => this;

    /// <summary>
    /// True for collations whose name carries the <c>_SC_</c>
    /// (supplementary-character-aware) flag, or whose version implicitly
    /// implies it (v140+). Real SQL Server's text functions — <c>LEN</c>,
    /// <c>SUBSTRING</c>, <c>LEFT</c>, <c>RIGHT</c>, <c>CHARINDEX</c>,
    /// <c>PATINDEX</c>, <c>STUFF</c>, <c>REVERSE</c>, <c>UNICODE</c> —
    /// switch from UTF-16 code-unit semantics to Unicode-codepoint
    /// semantics when this flag is set.
    /// </summary>
    internal virtual bool IsSupplementaryCharacterAware => false;

    /// <summary>
    /// The byte encoding the storage layer uses when this collation is
    /// pinned on a <c>varchar</c> / <c>char</c> column. Default is CP1252;
    /// <c>*_UTF8</c> collations override to <see cref="Encoding.UTF8"/>.
    /// Read by <see cref="VarcharSqlType.Encode"/> /
    /// <see cref="VarcharSqlType.Decode"/> / <see cref="VarcharSqlType.GetVariableByteCount"/>
    /// and the equivalent <see cref="CharSqlType"/> entry points; not
    /// consulted by nvarchar / nchar (UTF-16 storage is fixed).
    /// </summary>
    internal virtual Encoding StorageEncoding => CharSqlType.Cp1252Encoder;

    /// <summary>
    /// Generic culture-driven collation. Pins a
    /// <see cref="System.Globalization.CompareInfo"/> and a flag-derived
    /// <see cref="CompareOptions"/> set; routes <see cref="Compare"/> /
    /// <see cref="Equals"/> / <see cref="GetHashCode"/> through them.
    /// Sort options layer <see cref="CompareOptions.IgnoreSymbols"/> on
    /// top of the equality options, matching real SQL Server's sort-only
    /// ignore-symbols treatment (probe-confirmed across the SQL_*,
    /// Windows, and locale families).
    /// </summary>
    internal sealed class CultureCollation : Collation
    {
        private readonly string name;

        private readonly string description;

        private readonly bool caseSensitive;

        private readonly CompareInfo compareInfo;

        private readonly CompareOptions equalityOptions;

        private readonly CompareOptions sortOptions;

        private readonly Encoding storageEncoding;

        private readonly bool isSupplementaryCharacterAware;

        internal CultureCollation(string name, string description, string cultureName, bool caseSensitive, bool kanaTypeSensitive, bool widthSensitive, Encoding storageEncoding, bool isSupplementaryCharacterAware)
        {
            this.name = name;
            this.description = description;
            this.caseSensitive = caseSensitive;
            this.compareInfo = CultureInfo.GetCultureInfo(cultureName).CompareInfo;
            this.storageEncoding = storageEncoding;
            this.isSupplementaryCharacterAware = isSupplementaryCharacterAware;
            var baseOpts = caseSensitive
                ? CompareOptions.None
                : CompareOptions.IgnoreCase;
            // The _KS_ / _WS_ suffixes flip kanatype / width to *sensitive*.
            // Without them, SQL Server's "*_CI_AS" / "*_CS_AS" semantics
            // ignore both — full-width katakana / hiragana / half-width
            // katakana of the same logical character compare equal.
            if (!kanaTypeSensitive) baseOpts |= CompareOptions.IgnoreKanaType;
            if (!widthSensitive) baseOpts |= CompareOptions.IgnoreWidth;
            this.equalityOptions = baseOpts;
            // Sort layers IgnoreSymbols on top — probe-confirmed against
            // SQL Server 2025: every modeled family (SQL_*, Windows-style,
            // locale) treats apostrophe / hyphen as primary-weight-zero in
            // sort, while equality keeps them significant.
            this.sortOptions = baseOpts | CompareOptions.IgnoreSymbols;
        }

        public override string Name => this.name;

        public override string Description => this.description;

        public override bool CaseSensitive => this.caseSensitive;

        internal override Encoding StorageEncoding => this.storageEncoding;

        internal override bool IsSupplementaryCharacterAware => this.isSupplementaryCharacterAware;

        public override int Compare(string? x, string? y) =>
            x is null
                ? (y is null ? 0 : -1)
                : y is null ? 1 : this.compareInfo.Compare(x, y, this.sortOptions);

        public override bool Equals(string? x, string? y) =>
            x is null
                ? y is null
                : y is not null && this.compareInfo.Compare(x, y, this.equalityOptions) == 0;

        public override int GetHashCode(string obj) =>
            this.compareInfo.GetHashCode(obj, this.equalityOptions);
    }

    /// <summary>
    /// Generic binary collation. Models both the pre-2005 <c>_BIN</c> form
    /// (position-0 code-unit, position-1+ code-point) and the modern
    /// <c>_BIN2</c> form (pure UTF-16 code-unit ordinal). Substitutes a
    /// CP1252- or UTF-8-byte-aware sibling on varchar / char columns so the
    /// storage-encoding-specific byte order drives compare instead of
    /// UTF-16 code points.
    /// </summary>
    internal sealed class BinaryCollationBody : Collation
    {
        private readonly string name;

        private readonly string description;

        private readonly bool preBin2;

        private readonly Encoding storageEncoding;

        private readonly Collation varcharBody;

        internal BinaryCollationBody(string name, string description, bool preBin2, Encoding storageEncoding, Collation varcharBody)
        {
            this.name = name;
            this.description = description;
            this.preBin2 = preBin2;
            this.storageEncoding = storageEncoding;
            this.varcharBody = varcharBody;
        }

        public override string Name => this.name;

        public override string Description => this.description;

        public override bool CaseSensitive => true;

        internal override Encoding StorageEncoding => this.storageEncoding;

        internal override Collation ForVarcharStorage() => this.varcharBody;

        public override int Compare(string? x, string? y) =>
            x is null
                ? (y is null ? 0 : -1)
                : y is null ? 1 : this.preBin2 ? ComparePreBin2(x, y) : StringComparer.Ordinal.Compare(x, y);

        public override bool Equals(string? x, string? y) =>
            StringComparer.Ordinal.Equals(x, y);

        public override int GetHashCode(string obj) =>
            StringComparer.Ordinal.GetHashCode(obj);

        /// <summary>
        /// Pre-Bin2 (Latin1_General_BIN era) compare: position 0 reads as
        /// a 16-bit code unit (matches Bin2 at that position); positions
        /// 1+ combine surrogate pairs into 32-bit scalars before comparing
        /// (code-point order). Probe-confirmed against SQL Server 2025:
        /// applies uniformly to every <c>_BIN</c>-suffixed name regardless
        /// of locale or version.
        /// </summary>
        private static int ComparePreBin2(string x, string y)
        {
            var minLen = Math.Min(x.Length, y.Length);
            var i = 0;
            while (i < minLen)
            {
                int xVal, yVal, advance;
                if (i == 0)
                {
                    xVal = x[0];
                    yVal = y[0];
                    advance = 1;
                }
                else
                {
                    xVal = ScalarAt(x, i, out var xAdv);
                    yVal = ScalarAt(y, i, out _);
                    advance = xAdv;
                }
                if (xVal != yVal) return xVal.CompareTo(yVal);
                i += advance;
            }
            return x.Length.CompareTo(y.Length);
        }

        private static int ScalarAt(string s, int i, out int advance)
        {
            var c = s[i];
            if (char.IsHighSurrogate(c) && i + 1 < s.Length && char.IsLowSurrogate(s[i + 1]))
            {
                advance = 2;
                return char.ConvertToUtf32(c, s[i + 1]);
            }
            advance = 1;
            return c;
        }
    }

    /// <summary>
    /// CP1252-byte body for binary collations when pinned on a varchar /
    /// char column (non-UTF8 family). Encodes each operand to CP1252 then
    /// byte-compares — matches real SQL Server's BIN / BIN2 varchar sort
    /// and equality. <see cref="Name"/> is shared with the nvarchar-bodied
    /// sibling so catalog views report one collation name;
    /// <see cref="Resolve"/> treats them as the same collation for
    /// cross-operand coercibility.
    /// </summary>
    internal sealed class Cp1252BinaryCollation : Collation
    {
        private readonly string name;

        private readonly string description;

        internal Cp1252BinaryCollation(string name, string description)
        {
            this.name = name;
            this.description = description;
        }

        public override string Name => this.name;

        public override string Description => this.description;

        public override bool CaseSensitive => true;

        public override int Compare(string? x, string? y) =>
            x is null
                ? (y is null ? 0 : -1)
                : y is null ? 1 : CompareBytes(x, y);

        public override bool Equals(string? x, string? y) =>
            x is null
                ? y is null
                : y is not null && CompareBytes(x, y) == 0;

        public override int GetHashCode(string obj)
        {
            var bytes = CharSqlType.Cp1252Encoder.GetBytes(obj);
            var hash = default(HashCode);
            hash.AddBytes(bytes);
            return hash.ToHashCode();
        }

        private static int CompareBytes(string x, string y) =>
            CharSqlType.Cp1252Encoder.GetBytes(x).AsSpan().SequenceCompareTo(CharSqlType.Cp1252Encoder.GetBytes(y));
    }

    /// <summary>
    /// Codepoint-order body for <c>_BIN2_UTF8</c>-suffixed binary collations
    /// when pinned on a varchar / char column. Walks both operands as
    /// Unicode scalars (surrogate pairs combine into 32-bit codepoints
    /// before comparing), which equals UTF-8 byte order. <see cref="Name"/>
    /// is shared with the nvarchar-bodied sibling so catalog views report
    /// one collation name.
    /// </summary>
    internal sealed class Utf8CodepointBinaryCollation : Collation
    {
        private readonly string name;

        private readonly string description;

        internal Utf8CodepointBinaryCollation(string name, string description)
        {
            this.name = name;
            this.description = description;
        }

        public override string Name => this.name;

        public override string Description => this.description;

        public override bool CaseSensitive => true;

        internal override Encoding StorageEncoding => Encoding.UTF8;

        public override int Compare(string? x, string? y)
        {
            if (x is null) return y is null ? 0 : -1;
            if (y is null) return 1;
            var xIdx = 0;
            var yIdx = 0;
            while (xIdx < x.Length && yIdx < y.Length)
            {
                var xCp = ScalarAt(x, xIdx, out var xAdv);
                var yCp = ScalarAt(y, yIdx, out var yAdv);
                if (xCp != yCp) return xCp.CompareTo(yCp);
                xIdx += xAdv;
                yIdx += yAdv;
            }
            return (x.Length - xIdx).CompareTo(y.Length - yIdx);
        }

        public override bool Equals(string? x, string? y) =>
            x is null
                ? y is null
                : y is not null && Compare(x, y) == 0;

        public override int GetHashCode(string obj)
        {
            var bytes = Encoding.UTF8.GetBytes(obj);
            var hash = default(HashCode);
            hash.AddBytes(bytes);
            return hash.ToHashCode();
        }

        private static int ScalarAt(string s, int i, out int advance)
        {
            var c = s[i];
            if (char.IsHighSurrogate(c) && i + 1 < s.Length && char.IsLowSurrogate(s[i + 1]))
            {
                advance = 2;
                return char.ConvertToUtf32(c, s[i + 1]);
            }
            advance = 1;
            return c;
        }
    }
}
